## 06. Naver API

- client id = AvNig9fgyKtuz5gQ1ejx
- client secret = mPSQZav_Vx

In [1]:
# 네이버 검색 API 예제 - 블로그 검색
import os
import sys
import urllib.request
client_id = "AvNig9fgyKtuz5gQ1ejx"
client_secret = "mPSQZav_Vx"
encText = urllib.parse.quote("몰스킨")
url = "https://openapi.naver.com/v1/search/blog?query=" + encText # JSON 결과
# url = "https://openapi.naver.com/v1/search/blog.xml?query=" + encText # XML 결과
request = urllib.request.Request(url)
request.add_header("X-Naver-Client-Id",client_id)
request.add_header("X-Naver-Client-Secret",client_secret)
response = urllib.request.urlopen(request)
rescode = response.getcode()
if(rescode==200):
    response_body = response.read()
    print(response_body.decode('utf-8'))
else:
    print("Error Code:" + rescode)

{
	"lastBuildDate":"Sat, 04 Nov 2023 00:11:49 +0900",
	"total":50570,
	"start":1,
	"display":10,
	"items":[
		{
			"title":"베트남 스타벅스 2023 MD 달력 <b>몰스킨<\/b> 다이어리",
			"link":"https:\/\/gem87.tistory.com\/736",
			"description":"'2023년 <b>몰스킨<\/b> 다이어리'도 있는데, 이건 스타벅스 카드에 2.3 mil vnd 이상을 충전해야 하는 것이... 혹여나 쓴다 하여도 굳이 <b>몰스킨<\/b> 다이어리를 쓸 필요가 없기 때문에 포기. <b>몰스킨<\/b> 다이어리의 기본 가격이 꽤... ",
			"bloggername":"몽상가",
			"bloggerlink":"https:\/\/gem87.tistory.com\/",
			"postdate":"20221226"
		},
		{
			"title":"<b>몰스킨<\/b>과 기록 반평생 1편",
			"link":"https:\/\/blog.naver.com\/grimaldi\/223252240994",
			"description":"오늘의 주인공은 바로 <b>몰스킨<\/b> Moleskine입니다. 언젠가는 <b>몰스킨<\/b>에 대해 글을 쓸 날이 있을 것이라 생각했는데 타오바오에서 직구한 노트 4개가 도착한 것을 보다가 갑자기 글을 쓰게 되었습니다. 처음 <b>몰스킨<\/b>을... ",
			"bloggername":"미라클워커 브랜딩 저널",
			"bloggerlink":"blog.naver.com\/grimaldi",
			"postdate":"20231101"
		},
		{
			"title":"두 번째 모닝페이지 노트를 채우며 : 노트 비교(펜코, <b>몰스킨<\/b>)",
			"link":"https:\/\/blog.naver.com\/nanab9\/223041431750",
			"description":"세 번째 모닝페이지 노트는 <b>몰스킨<\/b> 클래식 룰드 하드커버 노트 라지 블랙 결론은 <b>몰스킨<\/b>이었다. 그리고 나는 그런 내 판단을 기록 첫날부터 후회하기 시작했다. 쿠팡에서 오랜만에 쇼핑하러 왔다며 5천 원이나... ",
			"bloggername":"책 속에 다락방",
			"bloggerlink":"blog.naver.com\/nanab9",
			"postdate":"20230311"
		},
		{
			"title":"<b>몰스킨<\/b> 각인과 심볼로 한해의 다이어리 만들기",
			"link":"https:\/\/blog.naver.com\/kim_la\/223248626234",
			"description":"짜잔~~~ 제가 고른 제품은 <b>몰스킨<\/b> 데일리, 하드커버, 색상은 스칼렛 레드 입니다 <b>몰스킨<\/b> 각인도 했고요 심볼도 달아줬어요 내지는 제가 올해 쓰고 싶은 방식과 적합한 '데일리' 내지로 골랐고요 내년엔... ",
			"bloggername":"자몽유자단 모여라",
			"bloggerlink":"blog.naver.com\/kim_la",
			"postdate":"20231029"
		},
		{
			"title":"<b>몰스킨<\/b> 2022-2023년 18개월 다이어리 위클리 소프트커버 XL... ",
			"link":"https:\/\/irubia.tistory.com\/489",
			"description":"저는 성인이 되고 난 이후에는 <b>몰스킨<\/b>의 위클리 다이어리를 계속 사용하고 있고, 최근 몇 년 간은... <b>몰스킨<\/b> 2022-23년 18개월 다이어리 위클리 소프트커버 XL 엑스라지에서 느끼는 웅장함 <b>몰스킨<\/b> 다이어리를... ",
			"bloggername":"irubia blog",
			"bloggerlink":"https:\/\/irubia.tistory.com\/",
			"postdate":"20221211"
		},
		{
			"title":"<b>몰스킨<\/b> 2024년 다이어리",
			"link":"https:\/\/blog.naver.com\/crystalai\/223229165127",
			"description":"매년 10월이면 구입하던 <b>몰스킨<\/b>을 사러 서점에 갔다왔다. 여기서도 <b>몰스킨<\/b>을 쓰는 사람들이 꾸준히 있는지 서점 한 코너에 <b>몰스킨<\/b> 코너가 있다. 하지만 매년 빈칸이 늘어가고 있고 내가 십여년간... ",
			"bloggername":"crystalあい♥",
			"bloggerlink":"blog.naver.com\/crystalai",
			"postdate":"20231005"
		},
		{
			"title":"핫트랙스 <b>몰스킨<\/b> vs 로이텀 노트 실사 비교 2023.10",
			"link":"https:\/\/blog.naver.com\/choihyunjini\/223241884136",
			"description":"안냐심까 퐝민수입니다 지난 포스팅에서 심도 있는 (?) <b>몰스킨<\/b> vs 로이텀 비교를 해보았는데요, 실사를 보고 결정해야 할 것 같아서 대구 핫트랙스를 찾아갔습니다 이 포스팅에서 얻을 수 있는 것: 1) <b>몰스킨<\/b>... ",
			"bloggername":"퐝항항항",
			"bloggerlink":"blog.naver.com\/choihyunjini",
			"postdate":"20231020"
		},
		{
			"title":"2024 <b>몰스킨<\/b> 데일리 포켓 하드커버 스칼렛레드",
			"link":"https:\/\/blog.naver.com\/soyoung7_7\/223242771372",
			"description":"나의 내년도 일기장 픽은 어김없이 <b>몰스킨<\/b> 데일리 하드커버 포켓 사이즈. 이것으로 열두 권째가 된다.... 내가 2014년에 <b>몰스킨<\/b> 데일리 포켓 '레드' 컬러를 사용했으니까 딱 10년 만에 다시 붉은 계열을 쓰게 됐다.... ",
			"bloggername":"숑알숑알 블로그",
			"bloggerlink":"blog.naver.com\/soyoung7_7",
			"postdate":"20231021"
		},
		{
			"title":"캐나다 여행 다이어리 여행 다이어리 <b>몰스킨<\/b> 다이어리 여행 후... ",
			"link":"https:\/\/blog.naver.com\/zinizinis2\/223253747883",
			"description":"캐나다 여행 다이어리 다이어리 - <b>몰스킨<\/b> 다이어리 2023.09.11 - 2023.09.21 이미 두 달 정도가 지났지만 다이어리를 보고 있으면 그때의 여행 기억이 새록새록 떠오른다. 마리오 오레오가 있어서 귀여워서 찰칵... ",
			"bloggername":"Present , 매일매일 선물같은 하루.",
			"bloggerlink":"blog.naver.com\/zinizinis2",
			"postdate":"20231102"
		},
		{
			"title":"좋은 일은 기억하기 \/<b>몰스킨<\/b> 불렛저널\/인더로우 책상 견적\/대전... ",
			"link":"https:\/\/blog.naver.com\/6636188\/223220800722",
			"description":"끝 <b>몰스킨<\/b> 불렛저널 나의 한달 지난 생일 선물 다이어리의 가격이 1년마다 오르는 관계로 더 이상 4만... 물론 <b>몰스킨<\/b>도 노트 중에 비싸긴 한데, 쓰던 다이어리보다 저렴하고 사이즈나 내지가 다양해서 완전... ",
			"bloggername":"취미도예가의 일",
			"bloggerlink":"blog.naver.com\/6636188",
			"postdate":"20230925"
		}
	]
}

In [5]:
response.code

200

In [11]:
#글자로 읽을 경우, decode utf-8 설정
response_body.decode("utf-8")

'{\n\t"lastBuildDate":"Fri, 03 Nov 2023 00:51:02 +0900",\n\t"total":2141,\n\t"start":1,\n\t"display":10,\n\t"items":[\n\t\t{\n\t\t\t"title":"[DAY ONE 서평] <b>폴라리스 랩소디<\\/b>: 제국의 공적 제1호... ",\n\t\t\t"link":"https:\\/\\/blog.naver.com\\/rkdudrkdud612\\/223141832024",\n\t\t\t"description":"<b>폴라리스 랩소디<\\/b>1: 제국의 공적 제1호 <b>폴라리스 랩소디<\\/b>2: Royal Blood\'s Gift 시작도 전에 겁을 지레 먹고 시작한 책. 판타지라는 장르와 총 8권까지 있는 대서사를 이루고 있다 하여 과연 이걸 다 읽을 수 있을까?... ",\n\t\t\t"bloggername":"Passionfruit",\n\t\t\t"bloggerlink":"blog.naver.com\\/rkdudrkdud612",\n\t\t\t"postdate":"20230629"\n\t\t},\n\t\t{\n\t\t\t"title":"2022062. <b>폴라리스 랩소디<\\/b>(1-5)",\n\t\t\t"link":"https:\\/\\/blog.naver.com\\/duky0909\\/222971408543",\n\t\t\t"description":"<b>폴라리스 랩소디<\\/b> 세트 양장본 Hardcover 저자 이영도 출판 황금가지 발매 2011.12.08. 올해의 마지막 책은 이영도의 <b>폴라리스 랩소디<\\/b> 이영도의 다른 작품과 다르게 호불호가 크게 갈리는 작품 물론 [퓨처 워커]... ",\n\t\t\t"bloggername":"Nautilus",\n\t\t\t"bloggerlink":"blog.naver.com\\/duky0909",\n\t\t\t"postdate":"20221231"\n\t\t},\n\t\t{\n\t\t\t"title":"☆☆☆ <b>폴라리스 랩소디<\\/b> 4 - 모루와 망치, 그리고 다섯번째의... ",\n\t\t\t"link":"https:\\/\\/blog.naver.com\\/greenmyth77\\/222818261482",\n\t\t\t"description":"<b>폴라리스 랩소디<\\/b> 4 저자 이영도 출판 황금가지 발매 2000.12.15. 선택한 것을 꾸준히 밀고 나가겠지만... &lt;<b>폴라리스 랩소디<\\/b> 4&gt; pp.200 휘리 노이에스의 진격을 막기 위해 두 명장이 나서고, 거침없이 나아가던 휘리가... ",\n\t\t\t"bloggername":"끝없는 이야기",\n\t\t\t"bloggerlink":"blog.naver.com\\/greenmyth77",\n\t\t\t"postdate":"20220719"\n\t\t},\n\t\t{\n\t\t\t"title":"[판타지003] <b>폴라리스 랩소디<\\/b>",\n\t\t\t"link":"https:\\/\\/blog.naver.com\\/magicbard\\/223198712433",\n\t\t\t"description":"최고의 영도좌의 작품을 꼽을때 꾸준히 거론되는 수작 4.5 \\/ 5 &lt;당장 보러가기&gt; &quot; #웹소설 #판타지 #판소 #웹소설추천 #판소추천 #판타지추천 #장르문학 #재밋는소설 #소설추천 #추천도서 #이영도 #<b>폴라리스랩소디<\\/b>... ",\n\t\t\t"bloggername":"환상문학록",\n\t\t\t"bloggerlink":"blog.naver.com\\/magicbard",\n\t\t\t"postdate":"20230831"\n\t\t},\n\t\t{\n\t\t\t"title":"<b>폴라리스 랩소디<\\/b>",\n\t\t\t"link":"https:\\/\\/blog.naver.com\\/jetlag0731\\/222664400059",\n\t\t\t"description":"<b>폴라리스 랩소디<\\/b> 1 저자 이영도 출판 황금가지 발매 2015.12.18. 이 책은 전에 제가 &quot;드래곤 라자&quot;라는 책을... -[<b>폴라리스 랩소디<\\/b> 중]키 드레이번- 왜 이 글귀가 인상이 깊었냐면, 이 책에서 각각의 등장인물의... ",\n\t\t\t"bloggername":"jetlag0731님의블로그",\n\t\t\t"bloggerlink":"blog.naver.com\\/jetlag0731",\n\t\t\t"postdate":"20220305"\n\t\t},\n\t\t{\n\t\t\t"title":"<b>폴라리스 랩소디<\\/b> (1~8) - 이영도",\n\t\t\t"link":"https:\\/\\/blog.naver.com\\/migurazi\\/223097242336",\n\t\t\t"description":"<b>폴라리스 랩소디<\\/b> 4 저자 이영도 출판 황금가지 발매 2000.12.15. 눈마새(눈물을 마시는 새)의 이영도 작가의 SF 소설. 예전에 인터넷을 떠돌던 Text 본을 보다가 말다가 한 기억이 어렴풋이 나는 것 같기도 하지만.... ",\n\t\t\t"bloggername":"mIgUrAzI bLog",\n\t\t\t"bloggerlink":"blog.naver.com\\/migurazi",\n\t\t\t"postdate":"20230509"\n\t\t},\n\t\t{\n\t\t\t"title":"<b>폴라리스 랩소디<\\/b>(이영도)",\n\t\t\t"link":"https:\\/\\/blog.naver.com\\/kittown\\/222089926962",\n\t\t\t"description":"다림-폴라리스 라트랑-에름 후작, 이루미나 공주 (+레모+바이스라: 삼국협정) 레갈루스-라이온, 새벽의 사수 <b>폴라리스 랩소디<\\/b>의 주제를 두 낱말로 말하자면 \'자유\'와 \'복수\'이다. 이 두 낱말은 우리가 보통... ",\n\t\t\t"bloggername":"루루의 일기장",\n\t\t\t"bloggerlink":"blog.naver.com\\/kittown",\n\t\t\t"postdate":"20200915"\n\t\t},\n\t\t{\n\t\t\t"title":"<b>폴라리스 랩소디<\\/b> 가상 캐스팅",\n\t\t\t"link":"https:\\/\\/blog.naver.com\\/xnwoddlek\\/221032515837",\n\t\t\t"description":"두고두고 읽는 이영도 시리즈 중, <b>폴라리스 랩소디<\\/b>가 가장 최근 양장판이 새로 나와서... 이 내맴속판타지 ㅋㅋㅋㅋ <b>폴라리스 랩소디<\\/b> 세트 저자 이영도 출판 황금가지 발매 2011.12.08.",\n\t\t\t"bloggername":"Nothing special",\n\t\t\t"bloggerlink":"blog.naver.com\\/xnwoddlek",\n\t\t\t"postdate":"20170619"\n\t\t},\n\t\t{\n\t\t\t"title":"이영도작가의 <b>폴라리스랩소디<\\/b> 양장판 POLARIS RHAPSODY... ",\n\t\t\t"link":"https:\\/\\/blog.naver.com\\/lv5photo\\/221250444570",\n\t\t\t"description":"이영도작가의 작품중 하나인 <b>폴라리스랩소디<\\/b>입니다. 총 5권이며 양장본으로 구입을 했습니다. 1권... <b>폴라리스 랩소디<\\/b> 바다와 해적 사나이의 이야기입니다. 이제 슬슬 읽어봐야겠습니다. 이영도 작가의... ",\n\t\t\t"bloggername":"LV5 Photographer",\n\t\t\t"bloggerlink":"blog.naver.com\\/lv5photo",\n\t\t\t"postdate":"20180412"\n\t\t},\n\t\t{\n\t\t\t"title":"<b>폴라리스 랩소디<\\/b> (Polaris Rhapsody).",\n\t\t\t"link":"https:\\/\\/blog.naver.com\\/sceneryofsunset\\/80198387559",\n\t\t\t"description":"<b>폴라리스 랩소디<\\/b> (Polaris Rhapsody) - 2000년 - 작가 이영도 - 출판사 황금가지 - 특이사항 8권 완결 대마법사 하이낙스의 영향으로 페인 제국이 쇠약해진 틈을 타, 4천여 해적을 이끌고 악명을 떨 치며 새로운 제국의... ",\n\t\t\t"bloggername":"노을진풍경에 매료되다..",\n\t\t\t"bloggerlink":"blog.naver.com\\/sceneryofsunset",\n\t\t\t"postdate":"20130921"\n\t\t}\n\t]\n}'

In [2]:
# 네이버 검색 API 예제 - 책 검색
import os
import sys
import urllib.request
client_id = "AvNig9fgyKtuz5gQ1ejx"
client_secret = "mPSQZav_Vx"
encText = urllib.parse.quote("폴라리스 랩소디")
url = "https://openapi.naver.com/v1/search/book?query=" + encText # JSON 결과
# url = "https://openapi.naver.com/v1/search/blog.xml?query=" + encText # XML 결과
request = urllib.request.Request(url)
request.add_header("X-Naver-Client-Id",client_id)
request.add_header("X-Naver-Client-Secret",client_secret)
response = urllib.request.urlopen(request)
rescode = response.getcode()
if(rescode==200):
    response_body = response.read()
    print(response_body.decode('utf-8'))
else:
    print("Error Code:" + rescode)

{
	"lastBuildDate":"Sat, 04 Nov 2023 00:11:57 +0900",
	"total":10,
	"start":1,
	"display":10,
	"items":[
		{
			"title":"폴라리스 랩소디 세트 (이영도 판타지 장편소설)",
			"link":"https:\/\/search.shopping.naver.com\/book\/catalog\/32491522107",
			"image":"https:\/\/shopping-phinf.pstatic.net\/main_3249152\/32491522107.20230525072205.jpg",
			"author":"이영도",
			"discount":"54000",
			"publisher":"황금가지",
			"pubdate":"20111208",
			"isbn":"9791158880316",
			"description":"《드래곤 라자》의 작가이자 한국의 대표적인 판타지 소설가 이영도의 대작 『폴라리스 랩소디 세트』. 지도, 그리고 기존 《폴라리스 랩소디》의 일러스트 중 독자들의 요청에 따라 김종수 씨 일러스트만을 남기고, 과거 폴라리스 랩소디 달력에 참여했던 김호용 씨의 일러스트 두 점을 새로 추가하였다. 총 8000여매에 달하는 이 소설은 저자의 전작들과는 달리 배경과 분위기를 새롭게 하고 있어 변신을 꾀하는 작품이라 볼 수 있다. 전작에서 드래곤이나 엘프 등이 심심치 않게 등장하고, 톨킨의 세계를 차용하였다면, 이번 작품에서는 인간이 중심으로 등장한다. \n\n제국력 1024년. 제국은 대마법사 하이낙스와의 오랜 전쟁 후 재건과 중흥의 열기로 가득했다. 그러나 각국의 함대가 전쟁으로 쇠락한 틈을 타고 키 '노스윈드' 드레이번의 해적선이 바다를 장악했다. 제국은 키 노스윈드에게 '제국의 공적 제1호' 현상을 걸었지만 이 해적단은 결혼을 위해 바다를 건너던 세기의 신부이자 카밀카르 왕국의 3공주 율리아나를 납치한다. 그러나 율리아나는 해적단의 노예 오스발의 도움으로 탈출하자, 키 노스윈드는 배를 버리고 그들의 뒤를 쫓는데……."
		},
		{
			"title":"폴라리스 랩소디 3: 새장 속의 왕 (이영도 판타지 장편소설)",
			"link":"https:\/\/search.shopping.naver.com\/book\/catalog\/32496596812",
			"image":"https:\/\/shopping-phinf.pstatic.net\/main_3249659\/32496596812.20221019115229.jpg",
			"author":"이영도",
			"discount":"13500",
			"publisher":"황금가지",
			"pubdate":"20151218",
			"isbn":"9791158880347",
			"description":"제국력 1024년. 제국은 대마법사 하이낙스와의 오랜 전쟁 후 재건과 중흥의 열기로 가득했다. 그러나 각국의 함대가 전쟁으로 쇠락한 틈을 타고 키 '노스윈드' 드레이번의 해적선이 바다를 장악했다. 제국은 키 노스윈드에게 '제국의 공적 제1호' 현상을 걸었지만 이 해적단은 결혼을 위해 바다를 건너던 세기의 신부이자 카밀카르 왕국의 3공주 율리아나를 납치한다. 그러나 율리아나는 해적단의 노예 오스발의 도움으로 탈출하자, 키 노스윈드는 배를 버리고 그들의 뒤를 쫓는데..."
		},
		{
			"title":"폴라리스 랩소디 4: 새벽의 사수 (이영도 판타지 장편소설)",
			"link":"https:\/\/search.shopping.naver.com\/book\/catalog\/32490346030",
			"image":"https:\/\/shopping-phinf.pstatic.net\/main_3249034\/32490346030.20221019132708.jpg",
			"author":"이영도",
			"discount":"13500",
			"publisher":"황금가지",
			"pubdate":"20151218",
			"isbn":"9791158880354",
			"description":"제국력 1024년. 제국은 대마법사 하이낙스와의 오랜 전쟁 후 재건과 중흥의 열기로 가득했다. 그러나 각국의 함대가 전쟁으로 쇠락한 틈을 타고 키 '노스윈드' 드레이번의 해적선이 바다를 장악했다. 제국은 키 노스윈드에게 '제국의 공적 제1호' 현상을 걸었지만 이 해적단은 결혼을 위해 바다를 건너던 세기의 신부이자 카밀카르 왕국의 3공주 율리아나를 납치한다. 그러나 율리아나는 해적단의 노예 오스발의 도움으로 탈출하자, 키 노스윈드는 배를 버리고 그들의 뒤를 쫓는데..."
		},
		{
			"title":"폴라리스 랩소디 5: 다섯 검의 주인 (이영도 판타지 장편소설)",
			"link":"https:\/\/search.shopping.naver.com\/book\/catalog\/32436246471",
			"image":"https:\/\/shopping-phinf.pstatic.net\/main_3243624\/32436246471.20221019135025.jpg",
			"author":"이영도",
			"discount":"13500",
			"publisher":"황금가지",
			"pubdate":"20151218",
			"isbn":"9791158880361",
			"description":"제국력 1024년. 제국은 대마법사 하이낙스와의 오랜 전쟁 후 재건과 중흥의 열기로 가득했다. 그러나 각국의 함대가 전쟁으로 쇠락한 틈을 타고 키 '노스윈드' 드레이번의 해적선이 바다를 장악했다. 제국은 키 노스윈드에게 '제국의 공적 제1호' 현상을 걸었지만 이 해적단은 결혼을 위해 바다를 건너던 세기의 신부이자 카밀카르 왕국의 3공주 율리아나를 납치한다. 그러나 율리아나는 해적단의 노예 오스발의 도움으로 탈출하자, 키 노스윈드는 배를 버리고 그들의 뒤를 쫓는데..."
		},
		{
			"title":"폴라리스 랩소디 1: 제국의 공적 제1호 (이영도 판타지 장편소설)",
			"link":"https:\/\/search.shopping.naver.com\/book\/catalog\/32485531779",
			"image":"https:\/\/shopping-phinf.pstatic.net\/main_3248553\/32485531779.20221019120305.jpg",
			"author":"이영도",
			"discount":"13500",
			"publisher":"황금가지",
			"pubdate":"20151218",
			"isbn":"9791158880323",
			"description":"제국력 1024년. 제국은 대마법사 하이낙스와의 오랜 전쟁 후 재건과 중흥의 열기로 가득했다. 그러나 각국의 함대가 전쟁으로 쇠락한 틈을 타고 키 '노스윈드' 드레이번의 해적선이 바다를 장악했다. 제국은 키 노스윈드에게 '제국의 공적 제1호' 현상을 걸었지만 이 해적단은 결혼을 위해 바다를 건너던 세기의 신부이자 카밀카르 왕국의 3공주 율리아나를 납치한다. 그러나 율리아나는 해적단의 노예 오스발의 도움으로 탈출하자, 키 노스윈드는 배를 버리고 그들의 뒤를 쫓는데..."
		},
		{
			"title":"폴라리스 랩소디 2: 구름이 고요 속을 흐를 때 (이영도 판타지 장편소설)",
			"link":"https:\/\/search.shopping.naver.com\/book\/catalog\/32505143711",
			"image":"https:\/\/shopping-phinf.pstatic.net\/main_3250514\/32505143711.20230919125931.jpg",
			"author":"이영도",
			"discount":"13500",
			"publisher":"황금가지",
			"pubdate":"20151218",
			"isbn":"9791158880330",
			"description":"제국력 1024년. 제국은 대마법사 하이낙스와의 오랜 전쟁 후 재건과 중흥의 열기로 가득했다. 그러나 각국의 함대가 전쟁으로 쇠락한 틈을 타고 키 '노스윈드' 드레이번의 해적선이 바다를 장악했다. 제국은 키 노스윈드에게 '제국의 공적 제1호' 현상을 걸었지만 이 해적단은 결혼을 위해 바다를 건너던 세기의 신부이자 카밀카르 왕국의 3공주 율리아나를 납치한다. 그러나 율리아나는 해적단의 노예 오스발의 도움으로 탈출하자, 키 노스윈드는 배를 버리고 그들의 뒤를 쫓는데..."
		},
		{
			"title":"폴라리스 랩소디 5 (제왕의 낙조)",
			"link":"https:\/\/search.shopping.naver.com\/book\/catalog\/32436012684",
			"image":"https:\/\/shopping-phinf.pstatic.net\/main_3243601\/32436012684.20221019135015.jpg",
			"author":"이영도",
			"discount":"0",
			"publisher":"황금가지",
			"pubdate":"20001215",
			"isbn":"9788982732751",
			"description":"와 를 냈던 지은이가 신작 를 펴냈다. 총 8000여매에 달하는 이 소설은 지은이의 전작들과는 달리 배경과 분위기를 새롭게 하고 있어 변신을 꾀하는 작품이라 볼 수 있다. 지은이의 전작에서 드래곤이나 엘프 등이 심심치 않게 등장하고, 톨킨의 세계를 차용하였다면, 이번 작품에서는 인간이 중심으로 등장한다. \n\n\n\n이 소설의 기본 골격이 되는 이야기는 바다를 질주하던 해적 무리들이 폴라리스라는 나라를 세워 정착하면서 겪는 1년 동안의 격정적인 삶이다. 여기에 제국의 오랜 전설 '다섯 왕자의 검'의 실현을 꾀하는 다벨 공국의 휘리 노이에스 정복 전쟁이 벌어진다. '다섯 왕자의 검'의 전설이란 네 군데의 땅과 한 사람을 가리키는 것으로, 이 전설의 실현을 위해 휘리 노이에스가 일으킨 정복전쟁으로 대륙은 불길에 휩싸이게 된다.\n\n\n\n인간의 세상에 직접 관여할 수 없는 이계(異界) 판데모니엄(지옥)의 지배자들(7명)이 인간 세상에 자유를 줄 것인지 복수를 할 것인지에 대한 투표를 한다. 이들의 투표에 따라 카코스 다에몬이라는 존재가 출현하게 될 것이다. 7명의 하이마스터들은 각자의 기준에 의해서 선택한 두 명 중 한 명의 인간을 선택하게 되는데 이들 각자가 표상하고 있는 것이 '자유'인지 '복수'인지에 따라 최종적으로 결정되는 것이다.\n\n\n\n이 소설 안에는 수많은 등장인물과 밝혀진 사실들보다는 지은이가 설정해 놓은 숨겨진 인물들과 밝혀내야 하는 무수한 세계가 있다. 가령 대륙의 9대 불가사의라든가, 키 드레이번에 앞서 '제국의 공적 1호'라 불렸던 대마법사 하이낙스, 그가 제국을 없애기 위해 벌였던 전쟁들, 판데모니엄의 하이마스터들, 변설의 요괴 린타 등이 그것이다. \n\n\n\n이러한 설정들은 판타지 문학에서 작품의 완결성을 높이는 근본적인 것으로 지은이의 데뷔작인 가 톨킨의 직접적인 영항을, 그리고 RPG 게임의 간접적 영향을 받았다면, 이번 작품에서는 지은이 자신이 설정한 세계를 드러냈다고 볼 수 있다.\n\n\n\n12\/28~ 31 사이에 출간될  가죽 양장본은 저자의 친필 사인과 고급 일러스트레이션 80여점이 들어 있다. 현재 양장본을 신청한 사람은 250여명으로 출판사에서는 500부만을 한정 제작할 계획이다. 가죽 양장본을 구입하는 사람에게는 반양장 단행본 1권을 증정한다. 가죽 양장본 구입은 황금가지 홈페이지에서 신청하면 된다."
		},
		{
			"title":"폴라리스 랩소디 2 (Royal Blood’s Gift)",
			"link":"https:\/\/search.shopping.naver.com\/book\/catalog\/32467016720",
			"image":"https:\/\/shopping-phinf.pstatic.net\/main_3246701\/32467016720.20221019123630.jpg",
			"author":"이영도",
			"discount":"7650",
			"publisher":"황금가지",
			"pubdate":"20001205",
			"isbn":"9788982732720",
			"description":"와 를 냈던 지은이가 신작 를 펴냈다. 총 8000여매에 달하는 이 소설은 지은이의 전작들과는 달리 배경과 분위기를 새롭게 하고 있어 변신을 꾀하는 작품이라 볼 수 있다. 지은이의 전작에서 드래곤이나 엘프 등이 심심치 않게 등장하고, 톨킨의 세계를 차용하였다면, 이번 작품에서는 인간이 중심으로 등장한다. \n\n\n\n이 소설의 기본 골격이 되는 이야기는 바다를 질주하던 해적 무리들이 폴라리스라는 나라를 세워 정착하면서 겪는 1년 동안의 격정적인 삶이다. 여기에 제국의 오랜 전설 '다섯 왕자의 검'의 실현을 꾀하는 다벨 공국의 휘리 노이에스 정복 전쟁이 벌어진다. '다섯 왕자의 검'의 전설이란 네 군데의 땅과 한 사람을 가리키는 것으로, 이 전설의 실현을 위해 휘리 노이에스가 일으킨 정복전쟁으로 대륙은 불길에 휩싸이게 된다.\n\n\n\n인간의 세상에 직접 관여할 수 없는 이계(異界) 판데모니엄(지옥)의 지배자들(7명)이 인간 세상에 자유를 줄 것인지 복수를 할 것인지에 대한 투표를 한다. 이들의 투표에 따라 카코스 다에몬이라는 존재가 출현하게 될 것이다. 7명의 하이마스터들은 각자의 기준에 의해서 선택한 두 명 중 한 명의 인간을 선택하게 되는데 이들 각자가 표상하고 있는 것이 '자유'인지 '복수'인지에 따라 최종적으로 결정되는 것이다.\n\n\n\n이 소설 안에는 수많은 등장인물과 밝혀진 사실들보다는 지은이가 설정해 놓은 숨겨진 인물들과 밝혀내야 하는 무수한 세계가 있다. 가령 대륙의 9대 불가사의라든가, 키 드레이번에 앞서 '제국의 공적 1호'라 불렸던 대마법사 하이낙스, 그가 제국을 없애기 위해 벌였던 전쟁들, 판데모니엄의 하이마스터들, 변설의 요괴 린타 등이 그것이다. \n\n\n\n이러한 설정들은 판타지 문학에서 작품의 완결성을 높이는 근본적인 것으로 지은이의 데뷔작인 가 톨킨의 직접적인 영항을, 그리고 RPG 게임의 간접적 영향을 받았다면, 이번 작품에서는 지은이 자신이 설정한 세계를 드러냈다고 볼 수 있다.\n\n\n\n12\/28~ 31 사이에 출간될  가죽 양장본은 저자의 친필 사인과 고급 일러스트레이션 80여점이 들어 있다. 현재 양장본을 신청한 사람은 250여명으로 출판사에서는 500부만을 한정 제작할 계획이다. 가죽 양장본을 구입하는 사람에게는 반양장 단행본 1권을 증정한다. 가죽 양장본 구입은 황금가지 홈페이지에서 신청하면 된다."
		},
		{
			"title":"폴라리스 랩소디 3 (죽지 않는 선장)",
			"link":"https:\/\/search.shopping.naver.com\/book\/catalog\/32496585803",
			"image":"https:\/\/shopping-phinf.pstatic.net\/main_3249658\/32496585803.20221019150410.jpg",
			"author":"이영도",
			"discount":"7650",
			"publisher":"황금가지",
			"pubdate":"20001205",
			"isbn":"9788982732737",
			"description":"와 를 냈던 지은이가 신작 를 펴냈다. 총 8000여매에 달하는 이 소설은 지은이의 전작들과는 달리 배경과 분위기를 새롭게 하고 있어 변신을 꾀하는 작품이라 볼 수 있다. 지은이의 전작에서 드래곤이나 엘프 등이 심심치 않게 등장하고, 톨킨의 세계를 차용하였다면, 이번 작품에서는 인간이 중심으로 등장한다. \n\n\n\n이 소설의 기본 골격이 되는 이야기는 바다를 질주하던 해적 무리들이 폴라리스라는 나라를 세워 정착하면서 겪는 1년 동안의 격정적인 삶이다. 여기에 제국의 오랜 전설 '다섯 왕자의 검'의 실현을 꾀하는 다벨 공국의 휘리 노이에스 정복 전쟁이 벌어진다. '다섯 왕자의 검'의 전설이란 네 군데의 땅과 한 사람을 가리키는 것으로, 이 전설의 실현을 위해 휘리 노이에스가 일으킨 정복전쟁으로 대륙은 불길에 휩싸이게 된다.\n\n\n\n인간의 세상에 직접 관여할 수 없는 이계(異界) 판데모니엄(지옥)의 지배자들(7명)이 인간 세상에 자유를 줄 것인지 복수를 할 것인지에 대한 투표를 한다. 이들의 투표에 따라 카코스 다에몬이라는 존재가 출현하게 될 것이다. 7명의 하이마스터들은 각자의 기준에 의해서 선택한 두 명 중 한 명의 인간을 선택하게 되는데 이들 각자가 표상하고 있는 것이 '자유'인지 '복수'인지에 따라 최종적으로 결정되는 것이다.\n\n\n\n이 소설 안에는 수많은 등장인물과 밝혀진 사실들보다는 지은이가 설정해 놓은 숨겨진 인물들과 밝혀내야 하는 무수한 세계가 있다. 가령 대륙의 9대 불가사의라든가, 키 드레이번에 앞서 '제국의 공적 1호'라 불렸던 대마법사 하이낙스, 그가 제국을 없애기 위해 벌였던 전쟁들, 판데모니엄의 하이마스터들, 변설의 요괴 린타 등이 그것이다. \n\n\n\n이러한 설정들은 판타지 문학에서 작품의 완결성을 높이는 근본적인 것으로 지은이의 데뷔작인 가 톨킨의 직접적인 영항을, 그리고 RPG 게임의 간접적 영향을 받았다면, 이번 작품에서는 지은이 자신이 설정한 세계를 드러냈다고 볼 수 있다.\n\n\n\n12\/28~ 31 사이에 출간될  가죽 양장본은 저자의 친필 사인과 고급 일러스트레이션 80여점이 들어 있다. 현재 양장본을 신청한 사람은 250여명으로 출판사에서는 500부만을 한정 제작할 계획이다. 가죽 양장본을 구입하는 사람에게는 반양장 단행본 1권을 증정한다. 가죽 양장본 구입은 황금가지 홈페이지에서 신청하면 된다."
		},
		{
			"title":"폴라리스 랩소디 4 (모루와 망치, 그리고 다섯번째의 검)",
			"link":"https:\/\/search.shopping.naver.com\/book\/catalog\/32506578696",
			"image":"https:\/\/shopping-phinf.pstatic.net\/main_3250657\/32506578696.20221019133127.jpg",
			"author":"이영도",
			"discount":"7650",
			"publisher":"황금가지",
			"pubdate":"20001215",
			"isbn":"9788982732744",
			"description":"와 를 냈던 지은이가 신작 를 펴냈다. 총 8000여매에 달하는 이 소설은 지은이의 전작들과는 달리 배경과 분위기를 새롭게 하고 있어 변신을 꾀하는 작품이라 볼 수 있다. 지은이의 전작에서 드래곤이나 엘프 등이 심심치 않게 등장하고, 톨킨의 세계를 차용하였다면, 이번 작품에서는 인간이 중심으로 등장한다. \n\n\n\n이 소설의 기본 골격이 되는 이야기는 바다를 질주하던 해적 무리들이 폴라리스라는 나라를 세워 정착하면서 겪는 1년 동안의 격정적인 삶이다. 여기에 제국의 오랜 전설 '다섯 왕자의 검'의 실현을 꾀하는 다벨 공국의 휘리 노이에스 정복 전쟁이 벌어진다. '다섯 왕자의 검'의 전설이란 네 군데의 땅과 한 사람을 가리키는 것으로, 이 전설의 실현을 위해 휘리 노이에스가 일으킨 정복전쟁으로 대륙은 불길에 휩싸이게 된다.\n\n\n\n인간의 세상에 직접 관여할 수 없는 이계(異界) 판데모니엄(지옥)의 지배자들(7명)이 인간 세상에 자유를 줄 것인지 복수를 할 것인지에 대한 투표를 한다. 이들의 투표에 따라 카코스 다에몬이라는 존재가 출현하게 될 것이다. 7명의 하이마스터들은 각자의 기준에 의해서 선택한 두 명 중 한 명의 인간을 선택하게 되는데 이들 각자가 표상하고 있는 것이 '자유'인지 '복수'인지에 따라 최종적으로 결정되는 것이다.\n\n\n\n이 소설 안에는 수많은 등장인물과 밝혀진 사실들보다는 지은이가 설정해 놓은 숨겨진 인물들과 밝혀내야 하는 무수한 세계가 있다. 가령 대륙의 9대 불가사의라든가, 키 드레이번에 앞서 '제국의 공적 1호'라 불렸던 대마법사 하이낙스, 그가 제국을 없애기 위해 벌였던 전쟁들, 판데모니엄의 하이마스터들, 변설의 요괴 린타 등이 그것이다. \n\n\n\n이러한 설정들은 판타지 문학에서 작품의 완결성을 높이는 근본적인 것으로 지은이의 데뷔작인 가 톨킨의 직접적인 영항을, 그리고 RPG 게임의 간접적 영향을 받았다면, 이번 작품에서는 지은이 자신이 설정한 세계를 드러냈다고 볼 수 있다.\n\n\n\n12\/28~ 31 사이에 출간될  가죽 양장본은 저자의 친필 사인과 고급 일러스트레이션 80여점이 들어 있다. 현재 양장본을 신청한 사람은 250여명으로 출판사에서는 500부만을 한정 제작할 계획이다. 가죽 양장본을 구입하는 사람에게는 반양장 단행본 1권을 증정한다. 가죽 양장본 구입은 황금가지 홈페이지에서 신청하면 된다."
		}
	]
}

In [8]:
# 네이버 검색 API 예제 - 영화 검색
import os
import sys
import urllib.request
client_id = "AvNig9fgyKtuz5gQ1ejx"
client_secret = "mPSQZav_Vx"
encText = urllib.parse.quote("해리포터")
url = "https://openapi.naver.com/v1/search/movie?query=" + encText # JSON 결과
# url = "https://openapi.naver.com/v1/search/blog.xml?query=" + encText # XML 결과
request = urllib.request.Request(url)
request.add_header("X-Naver-Client-Id",client_id)
request.add_header("X-Naver-Client-Secret",client_secret)
response = urllib.request.urlopen(request)
rescode = response.getcode()
if(rescode==200):
    response_body = response.read()
    print(response_body.decode('utf-8'))
else:
    print("Error Code:" + rescode)

HTTPError: HTTP Error 404: Not Found

In [10]:
import os
import sys
import urllib.request
client_id = "AvNig9fgyKtuz5gQ1ejx"
client_secret = "mPSQZav_Vx"
encText = urllib.parse.quote("몰스킨")
url = "https://openapi.naver.com/v1/search/shop?query=" + encText # JSON 결과
# url = "https://openapi.naver.com/v1/search/blog.xml?query=" + encText # XML 결과
request = urllib.request.Request(url)
request.add_header("X-Naver-Client-Id",client_id)
request.add_header("X-Naver-Client-Secret",client_secret)
response = urllib.request.urlopen(request)
rescode = response.getcode()
if(rescode==200):
    response_body = response.read()
    print(response_body.decode('utf-8'))
else:
    print("Error Code:" + rescode)

{
	"lastBuildDate":"Sat, 04 Nov 2023 00:42:06 +0900",
	"total":43212,
	"start":1,
	"display":10,
	"items":[
		{
			"title":"스타벅스 2024 <b>몰스킨<\/b> 다이어리 데일리 플래너 일기장 노트 스벅 카페 겨울 윈터 e프리퀀시",
			"link":"https:\/\/search.shopping.naver.com\/gate.nhn?id=86963344737",
			"image":"https:\/\/shopping-phinf.pstatic.net\/main_8696334\/86963344737.17.jpg",
			"lprice":"49000",
			"hprice":"",
			"mallName":"유니스스토어",
			"productId":"86963344737",
			"productType":"2",
			"brand":"스타벅스",
			"maker":"몰스킨",
			"category1":"생활\/건강",
			"category2":"문구\/사무용품",
			"category3":"다이어리\/플래너",
			"category4":"다이어리"
		},
		{
			"title":"<b>몰스킨<\/b> 2024 위클리 다이어리 포켓 상품선택",
			"link":"https:\/\/search.shopping.naver.com\/gate.nhn?id=42445452123",
			"image":"https:\/\/shopping-phinf.pstatic.net\/main_4244545\/42445452123.20230906151250.jpg",
			"lprice":"29640",
			"hprice":"",
			"mallName":"네이버",
			"productId":"42445452123",
			"productType":"1",
			"brand":"몰스킨",
			"maker":"",
			"category1":"생활\/건강",
			"category2":"문구\/사무용품",
			"category3":"다이어리\/플래너",
			"category4":"다이어리"
		},
		{
			"title":"올젠 남성 가을겨울 <b>몰스킨<\/b> 자켓 ZOC3KG13122",
			"link":"https:\/\/search.shopping.naver.com\/gate.nhn?id=41898585909",
			"image":"https:\/\/shopping-phinf.pstatic.net\/main_4189858\/41898585909.20231028172014.jpg",
			"lprice":"70390",
			"hprice":"",
			"mallName":"네이버",
			"productId":"41898585909",
			"productType":"1",
			"brand":"",
			"maker":"",
			"category1":"패션의류",
			"category2":"남성의류",
			"category3":"재킷",
			"category4":""
		},
		{
			"title":"인디안 INDIAN 오리지널 <b>몰스킨<\/b> 셋업 자켓 MITFAWF9101",
			"link":"https:\/\/search.shopping.naver.com\/gate.nhn?id=39838076389",
			"image":"https:\/\/shopping-phinf.pstatic.net\/main_3983807\/39838076389.20230507104902.jpg",
			"lprice":"56110",
			"hprice":"",
			"mallName":"네이버",
			"productId":"39838076389",
			"productType":"1",
			"brand":"인디안",
			"maker":"",
			"category1":"패션의류",
			"category2":"남성의류",
			"category3":"재킷",
			"category4":""
		},
		{
			"title":"로이텀 2024 다이어리 데일리 하드커버 A5",
			"link":"https:\/\/search.shopping.naver.com\/gate.nhn?id=86743260710",
			"image":"https:\/\/shopping-phinf.pstatic.net\/main_8674326\/86743260710.1.jpg",
			"lprice":"31450",
			"hprice":"",
			"mallName":"몰스킨스토어",
			"productId":"86743260710",
			"productType":"2",
			"brand":"로이텀",
			"maker":"로이텀",
			"category1":"생활\/건강",
			"category2":"문구\/사무용품",
			"category3":"다이어리\/플래너",
			"category4":"다이어리"
		},
		{
			"title":"<b>몰스킨<\/b> 2024 데일리 다이어리 포켓 상품선택",
			"link":"https:\/\/search.shopping.naver.com\/gate.nhn?id=42473541158",
			"image":"https:\/\/shopping-phinf.pstatic.net\/main_4247354\/42473541158.20230907073601.jpg",
			"lprice":"31420",
			"hprice":"",
			"mallName":"네이버",
			"productId":"42473541158",
			"productType":"1",
			"brand":"몰스킨",
			"maker":"",
			"category1":"생활\/건강",
			"category2":"문구\/사무용품",
			"category3":"다이어리\/플래너",
			"category4":"다이어리"
		},
		{
			"title":"<b>몰스킨<\/b> 2024 위클리 다이어리 라지 상품선택",
			"link":"https:\/\/search.shopping.naver.com\/gate.nhn?id=42444253256",
			"image":"https:\/\/shopping-phinf.pstatic.net\/main_4244425\/42444253256.20230906161929.jpg",
			"lprice":"38760",
			"hprice":"",
			"mallName":"네이버",
			"productId":"42444253256",
			"productType":"1",
			"brand":"몰스킨",
			"maker":"몰스킨",
			"category1":"생활\/건강",
			"category2":"문구\/사무용품",
			"category3":"다이어리\/플래너",
			"category4":"다이어리"
		},
		{
			"title":"<b>몰스킨<\/b> 2024 다이어리 클래식 소프트커버 위클리 포켓 2024년 24년",
			"link":"https:\/\/search.shopping.naver.com\/gate.nhn?id=86678199160",
			"image":"https:\/\/shopping-phinf.pstatic.net\/main_8667819\/86678199160.2.jpg",
			"lprice":"32400",
			"hprice":"",
			"mallName":"베스트펜",
			"productId":"86678199160",
			"productType":"2",
			"brand":"몰스킨",
			"maker":"몰스킨",
			"category1":"생활\/건강",
			"category2":"문구\/사무용품",
			"category3":"다이어리\/플래너",
			"category4":"다이어리"
		},
		{
			"title":"올젠 남성 <b>몰스킨<\/b> 스판 바지 ZOC3PP1312",
			"link":"https:\/\/search.shopping.naver.com\/gate.nhn?id=42934495004",
			"image":"https:\/\/shopping-phinf.pstatic.net\/main_4293449\/42934495004.20231015070059.jpg",
			"lprice":"34840",
			"hprice":"",
			"mallName":"네이버",
			"productId":"42934495004",
			"productType":"1",
			"brand":"",
			"maker":"",
			"category1":"패션의류",
			"category2":"남성의류",
			"category3":"바지",
			"category4":""
		},
		{
			"title":"<b>몰스킨<\/b> 2024 데일리 다이어리 라지 상품선택",
			"link":"https:\/\/search.shopping.naver.com\/gate.nhn?id=42444257103",
			"image":"https:\/\/shopping-phinf.pstatic.net\/main_4244425\/42444257103.20230906055621.jpg",
			"lprice":"40850",
			"hprice":"",
			"mallName":"네이버",
			"productId":"42444257103",
			"productType":"1",
			"brand":"몰스킨",
			"maker":"",
			"category1":"생활\/건강",
			"category2":"문구\/사무용품",
			"category3":"다이어리\/플래너",
			"category4":"다이어리"
		}
	]
}

In [31]:
def gen_search_url(api_node, search_text, start_num, disp_num):
    base = 'https://openapi.naver.com/v1/search'
    node = '/'+api_node+'.json'
    param_query = '?query=' + urllib.parse.quote(search_text)
    param_start = '&start=' + str(start_num)
    param_disp = '&display=' + str(disp_num)
    
    return base + node + param_query + param_start + param_disp

In [32]:
gen_search_url('shop','TEST',10,3)

'https://openapi.naver.com/v1/search/shop.json?query=TEST&start=10&display=3'

## get result onpage()

In [18]:
import json
import datetime

def get_result_onpage(url):
    request.add_header("X-Naver-Client-Id",client_id)
    request.add_header("X-Naver-Client-Secret",client_secret)
    response = urllib.request.urlopen(request)
    print('[%s] Url Request Success'% datetime.datetime.now())
    return json.loads(response.read().decode('utf-8'))

In [33]:
datetime.datetime.now()

datetime.datetime(2023, 11, 4, 0, 59, 6, 593334)

In [34]:
url = gen_search_url('shop','몰스킨',1,5)
one_result = get_result_onpage(url)

[2023-11-04 00:59:08.790513] Url Request Success

In [35]:
one_result

{'lastBuildDate': 'Sat, 04 Nov 2023 00:59:08 +0900',
 'total': 43214,
 'start': 1,
 'display': 10,
 'items': [{'title': '스타벅스 2024 <b>몰스킨</b> 다이어리 데일리 플래너 일기장 노트 스벅 카페 겨울 윈터 e프리퀀시',
   'link': 'https://search.shopping.naver.com/gate.nhn?id=86963344737',
   'image': 'https://shopping-phinf.pstatic.net/main_8696334/86963344737.17.jpg',
   'lprice': '49000',
   'hprice': '',
   'mallName': '유니스스토어',
   'productId': '86963344737',
   'productType': '2',
   'brand': '스타벅스',
   'maker': '몰스킨',
   'category1': '생활/건강',
   'category2': '문구/사무용품',
   'category3': '다이어리/플래너',
   'category4': '다이어리'},
  {'title': '<b>몰스킨</b> 2024 위클리 다이어리 포켓 상품선택',
   'link': 'https://search.shopping.naver.com/gate.nhn?id=42445452123',
   'image': 'https://shopping-phinf.pstatic.net/main_4244545/42445452123.20230906151250.jpg',
   'lprice': '29640',
   'hprice': '',
   'mallName': '네이버',
   'productId': '42445452123',
   'productType': '1',
   'brand': '몰스킨',
   'maker': '',
   'category1': '생활/건강',
   'category2': '문구/사무용품',
   'category3': '다이어리/플래너',
   'category4': '다이어리'},
  {'title': '올젠 남성 가을겨울 <b>몰스킨</b> 자켓 ZOC3KG13122',
   'link': 'https://search.shopping.naver.com/gate.nhn?id=41898585909',
   'image': 'https://shopping-phinf.pstatic.net/main_4189858/41898585909.20231028172014.jpg',
   'lprice': '70390',
   'hprice': '',
   'mallName': '네이버',
   'productId': '41898585909',
   'productType': '1',
   'brand': '',
   'maker': '',
   'category1': '패션의류',
   'category2': '남성의류',
   'category3': '재킷',
   'category4': ''},
  {'title': '인디안 INDIAN 오리지널 <b>몰스킨</b> 셋업 자켓 MITFAWF9101',
   'link': 'https://search.shopping.naver.com/gate.nhn?id=39838076389',
   'image': 'https://shopping-phinf.pstatic.net/main_3983807/39838076389.20230507104902.jpg',
   'lprice': '56110',
   'hprice': '',
   'mallName': '네이버',
   'productId': '39838076389',
   'productType': '1',
   'brand': '인디안',
   'maker': '',
   'category1': '패션의류',
   'category2': '남성의류',
   'category3': '재킷',
   'category4': ''},
  {'title': '로이텀 2024 다이어리 데일리 하드커버 A5',
   'link': 'https://search.shopping.naver.com/gate.nhn?id=86743260710',
   'image': 'https://shopping-phinf.pstatic.net/main_8674326/86743260710.1.jpg',
   'lprice': '31450',
   'hprice': '',
   'mallName': '몰스킨스토어',
   'productId': '86743260710',
   'productType': '2',
   'brand': '로이텀',
   'maker': '로이텀',
   'category1': '생활/건강',
   'category2': '문구/사무용품',
   'category3': '다이어리/플래너',
   'category4': '다이어리'},
  {'title': '<b>몰스킨</b> 2024 데일리 다이어리 포켓 상품선택',
   'link': 'https://search.shopping.naver.com/gate.nhn?id=42473541158',
   'image': 'https://shopping-phinf.pstatic.net/main_4247354/42473541158.20230907073601.jpg',
   'lprice': '31420',
   'hprice': '',
   'mallName': '네이버',
   'productId': '42473541158',
   'productType': '1',
   'brand': '몰스킨',
   'maker': '',
   'category1': '생활/건강',
   'category2': '문구/사무용품',
   'category3': '다이어리/플래너',
   'category4': '다이어리'},
  {'title': '<b>몰스킨</b> 2024 위클리 다이어리 라지 상품선택',
   'link': 'https://search.shopping.naver.com/gate.nhn?id=42444253256',
   'image': 'https://shopping-phinf.pstatic.net/main_4244425/42444253256.20230906161929.jpg',
   'lprice': '38760',
   'hprice': '',
   'mallName': '네이버',
   'productId': '42444253256',
   'productType': '1',
   'brand': '몰스킨',
   'maker': '몰스킨',
   'category1': '생활/건강',
   'category2': '문구/사무용품',
   'category3': '다이어리/플래너',
   'category4': '다이어리'},
  {'title': '<b>몰스킨</b> 2024 다이어리 클래식 소프트커버 위클리 포켓 2024년 24년',
   'link': 'https://search.shopping.naver.com/gate.nhn?id=86678199160',
   'image': 'https://shopping-phinf.pstatic.net/main_8667819/86678199160.2.jpg',
   'lprice': '32400',
   'hprice': '',
   'mallName': '베스트펜',
   'productId': '86678199160',
   'productType': '2',
   'brand': '몰스킨',
   'maker': '몰스킨',
   'category1': '생활/건강',
   'category2': '문구/사무용품',
   'category3': '다이어리/플래너',
   'category4': '다이어리'},
  {'title': '올젠 남성 <b>몰스킨</b> 스판 바지 ZOC3PP1312',
   'link': 'https://search.shopping.naver.com/gate.nhn?id=42934495004',
   'image': 'https://shopping-phinf.pstatic.net/main_4293449/42934495004.20231015070059.jpg',
   'lprice': '34840',
   'hprice': '',
   'mallName': '네이버',
   'productId': '42934495004',
   'productType': '1',
   'brand': '',
   'maker': '',
   'category1': '패션의류',
   'category2': '남성의류',
   'category3': '바지',
   'category4': ''},
  {'title': '<b>몰스킨</b> 2024 데일리 다이어리 라지 상품선택',
   'link': 'https://search.shopping.naver.com/gate.nhn?id=42444257103',
   'image': 'https://shopping-phinf.pstatic.net/main_4244425/42444257103.20230906055621.jpg',
   'lprice': '40850',
   'hprice': '',
   'mallName': '네이버',
   'productId': '42444257103',
   'productType': '1',
   'brand': '몰스킨',
   'maker': '',
   'category1': '생활/건강',
   'category2': '문구/사무용품',
   'category3': '다이어리/플래너',
   'category4': '다이어리'}]}

In [36]:
one_result['items'][0]['title']

'스타벅스 2024 <b>몰스킨</b> 다이어리 데일리 플래너 일기장 노트 스벅 카페 겨울 윈터 e프리퀀시'

In [47]:
import pandas as pd

def get_fields(json_data):
    title = [delete_tag(each['title']) for each in json_data['items']]
    link = [each['link'] for each in json_data['items']]
    lprice = [each['lprice'] for each in json_data['items']]
    mallName = [each['mallName'] for each in json_data['items']]
    
    result_pd = pd.DataFrame({
        "title":title,
        "link":link,
        "lprice":lprice,
        "mall":mallName,}, columns = ['title','lprice','link','mall']
    )
    return result_pd

In [41]:
get_fields(one_result)

,title,lprice,link,mall
0,스타벅스 2024 <b>몰스킨</b> 다이어리 데일리 플래너 일기장 노트 스벅 카페...,49000,https://search.shopping.naver.com/gate.nhn?id=...,유니스스토어
1,<b>몰스킨</b> 2024 위클리 다이어리 포켓 상품선택,29640,https://search.shopping.naver.com/gate.nhn?id=...,네이버
2,올젠 남성 가을겨울 <b>몰스킨</b> 자켓 ZOC3KG13122,70390,https://search.shopping.naver.com/gate.nhn?id=...,네이버
3,인디안 INDIAN 오리지널 <b>몰스킨</b> 셋업 자켓 MITFAWF9101,56110,https://search.shopping.naver.com/gate.nhn?id=...,네이버
4,로이텀 2024 다이어리 데일리 하드커버 A5,31450,https://search.shopping.naver.com/gate.nhn?id=...,몰스킨스토어
5,<b>몰스킨</b> 2024 데일리 다이어리 포켓 상품선택,31420,https://search.shopping.naver.com/gate.nhn?id=...,네이버
6,<b>몰스킨</b> 2024 위클리 다이어리 라지 상품선택,38760,https://search.shopping.naver.com/gate.nhn?id=...,네이버
7,<b>몰스킨</b> 2024 다이어리 클래식 소프트커버 위클리 포켓 2024년 24년,32400,https://search.shopping.naver.com/gate.nhn?id=...,베스트펜
8,올젠 남성 <b>몰스킨</b> 스판 바지 ZOC3PP1312,34840,https://search.shopping.naver.com/gate.nhn?id=...,네이버
9,<b>몰스킨</b> 2024 데일리 다이어리 라지 상품선택,40850,https://search.shopping.naver.com/gate.nhn?id=...,네이버

In [48]:
def delete_tag(input_str):
    input_str = input_str.replace("<b>","")
    input_str = input_str.replace("</b>","")                            
    return input_str

In [52]:
get_fields(one_result)

,title,lprice,link,mall
0,스타벅스 2024 몰스킨 다이어리 데일리 플래너 일기장 노트 스벅 카페 겨울 윈터 ...,49000,https://search.shopping.naver.com/gate.nhn?id=...,유니스스토어
1,몰스킨 2024 위클리 다이어리 포켓 상품선택,29640,https://search.shopping.naver.com/gate.nhn?id=...,네이버
2,올젠 남성 가을겨울 몰스킨 자켓 ZOC3KG13122,70390,https://search.shopping.naver.com/gate.nhn?id=...,네이버
3,인디안 INDIAN 오리지널 몰스킨 셋업 자켓 MITFAWF9101,56110,https://search.shopping.naver.com/gate.nhn?id=...,네이버
4,로이텀 2024 다이어리 데일리 하드커버 A5,31450,https://search.shopping.naver.com/gate.nhn?id=...,몰스킨스토어
5,몰스킨 2024 데일리 다이어리 포켓 상품선택,31420,https://search.shopping.naver.com/gate.nhn?id=...,네이버
6,몰스킨 2024 위클리 다이어리 라지 상품선택,38760,https://search.shopping.naver.com/gate.nhn?id=...,네이버
7,몰스킨 2024 다이어리 클래식 소프트커버 위클리 포켓 2024년 24년,32400,https://search.shopping.naver.com/gate.nhn?id=...,베스트펜
8,올젠 남성 몰스킨 스판 바지 ZOC3PP1312,34840,https://search.shopping.naver.com/gate.nhn?id=...,네이버
9,몰스킨 2024 데일리 다이어리 라지 상품선택,40850,https://search.shopping.naver.com/gate.nhn?id=...,네이버

In [54]:
url = gen_search_url('shop','몰스킨',1,5)
json_result = get_result_onpage(url)

[2023-11-04 01:08:52.757645] Url Request Success

In [56]:
pd_result = get_fields(json_result)

In [58]:
pd_result

,title,lprice,link,mall
0,스타벅스 2024 몰스킨 다이어리 데일리 플래너 일기장 노트 스벅 카페 겨울 윈터 ...,49000,https://search.shopping.naver.com/gate.nhn?id=...,유니스스토어
1,몰스킨 2024 위클리 다이어리 포켓 상품선택,29640,https://search.shopping.naver.com/gate.nhn?id=...,네이버
2,올젠 남성 가을겨울 몰스킨 자켓 ZOC3KG13122,70390,https://search.shopping.naver.com/gate.nhn?id=...,네이버
3,인디안 INDIAN 오리지널 몰스킨 셋업 자켓 MITFAWF9101,56110,https://search.shopping.naver.com/gate.nhn?id=...,네이버
4,로이텀 2024 다이어리 데일리 하드커버 A5,31450,https://search.shopping.naver.com/gate.nhn?id=...,몰스킨스토어
5,몰스킨 2024 데일리 다이어리 포켓 상품선택,31420,https://search.shopping.naver.com/gate.nhn?id=...,네이버
6,몰스킨 2024 위클리 다이어리 라지 상품선택,38760,https://search.shopping.naver.com/gate.nhn?id=...,네이버
7,몰스킨 2024 다이어리 클래식 소프트커버 위클리 포켓 2024년 24년,32400,https://search.shopping.naver.com/gate.nhn?id=...,베스트펜
8,올젠 남성 몰스킨 스판 바지 ZOC3PP1312,34840,https://search.shopping.naver.com/gate.nhn?id=...,네이버
9,몰스킨 2024 데일리 다이어리 라지 상품선택,40850,https://search.shopping.naver.com/gate.nhn?id=...,네이버

## actmain()

In [60]:
for n in range(1,1000,100):
    print(n)

1
101
201
301
401
501
601
701
801
901

In [70]:
result_mol = []

for n in range(1,1000,100):
    url = gen_search_url('shop','몰스킨',n,100)
    json_result = get_result_onpage(url)
    pd_result = get_fields(json_result)
    
    result_mol.append(pd_result)
result_mol = pd.concat(result_mol)

[2023-11-04 01:17:04.935530] Url Request Success
[2023-11-04 01:17:05.419654] Url Request Success
[2023-11-04 01:17:05.855752] Url Request Success
[2023-11-04 01:17:06.296852] Url Request Success
[2023-11-04 01:17:06.742953] Url Request Success
[2023-11-04 01:17:07.214062] Url Request Success
[2023-11-04 01:17:07.662163] Url Request Success
[2023-11-04 01:17:08.109277] Url Request Success
[2023-11-04 01:17:08.596400] Url Request Success
[2023-11-04 01:17:09.040500] Url Request Success

In [69]:
result_mol.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   title   100 non-null    object
 1   lprice  100 non-null    object
 2   link    100 non-null    object
 3   mall    100 non-null    object
dtypes: object(4)
memory usage: 3.9+ KB

In [74]:
result_mol.reset_index(drop=True, inplace=True)
result_mol.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   title   100 non-null    object
 1   lprice  100 non-null    object
 2   link    100 non-null    object
 3   mall    100 non-null    object
dtypes: object(4)
memory usage: 3.2+ KB

In [75]:
result_mol.head()

,title,lprice,link,mall
0,스타벅스 2024 몰스킨 다이어리 데일리 플래너 일기장 노트 스벅 카페 겨울 윈터 ...,49000,https://search.shopping.naver.com/gate.nhn?id=...,유니스스토어
1,몰스킨 2024 위클리 다이어리 포켓 상품선택,29640,https://search.shopping.naver.com/gate.nhn?id=...,네이버
2,올젠 남성 가을겨울 몰스킨 자켓 ZOC3KG13122,70390,https://search.shopping.naver.com/gate.nhn?id=...,네이버
3,인디안 INDIAN 오리지널 몰스킨 셋업 자켓 MITFAWF9101,56110,https://search.shopping.naver.com/gate.nhn?id=...,네이버
4,로이텀 2024 다이어리 데일리 하드커버 A5,31450,https://search.shopping.naver.com/gate.nhn?id=...,몰스킨스토어