In [9]:
import mysql.connector

In [6]:
mydb = mysql.connector.connect(
    host = 'localhost',
    user='root',
    password="7063",
    database = 'zerobase'
)



mydb.close()

In [8]:
remote = mysql.connector.connect(
    host = 'database-1.cjnz1ulpkijp.ap-southeast-2.rds.amazonaws.com',
    port=3306,
    user='admin',
    password="mooltisue305!",
    database = 'zerobase')

In [22]:
import pandas as pd
import xlrd
df = pd.read_csv("C:/Users/shchoi/Downloads/제로-베이스---데이터-사이언스-스쿨---강의자료---part-01---05--230120- (2)/Part 04. EDA & Part 05. SQL/2020_crime.csv", sep=",", encoding='cp949')
df.tail()

     구분     죄종 발생검거    건수
305  수서  강간,추행   검거   194
306  수서     절도   발생  1010
307  수서     절도   검거   475
308  수서     폭력   발생  1394
309  수서     폭력   검거  1200

In [28]:

sql = """Insert into crime_status Values("2020",%s,%s,%s,%s)"""
cursor = remote.cursor(buffered=True)

In [30]:
for i,rows in df.iterrows():
    cursor.execute(sql,tuple(rows))
    print(tuple(rows))
    remote.commit()

('중부', '살인', '발생', 1)
('중부', '살인', '검거', 1)
('중부', '강도', '발생', 3)
('중부', '강도', '검거', 4)
('중부', '강간,추행', '발생', 113)
('중부', '강간,추행', '검거', 76)
('중부', '절도', '발생', 943)
('중부', '절도', '검거', 495)
('중부', '폭력', '발생', 997)
('중부', '폭력', '검거', 830)
('종로', '살인', '발생', 9)
('종로', '살인', '검거', 6)
('종로', '강도', '발생', 4)
('종로', '강도', '검거', 4)
('종로', '강간,추행', '발생', 115)
('종로', '강간,추행', '검거', 93)
('종로', '절도', '발생', 602)
('종로', '절도', '검거', 284)
('종로', '폭력', '발생', 964)
('종로', '폭력', '검거', 792)
('남대문', '살인', '발생', 1)
('남대문', '살인', '검거', 1)
('남대문', '강도', '발생', 2)
('남대문', '강도', '검거', 2)
('남대문', '강간,추행', '발생', 73)
('남대문', '강간,추행', '검거', 52)
('남대문', '절도', '발생', 699)
('남대문', '절도', '검거', 368)
('남대문', '폭력', '발생', 579)
('남대문', '폭력', '검거', 494)
('서대문', '살인', '발생', 3)
('서대문', '살인', '검거', 3)
('서대문', '강도', '발생', 2)
('서대문', '강도', '검거', 1)
('서대문', '강간,추행', '발생', 159)
('서대문', '강간,추행', '검거', 149)
('서대문', '절도', '발생', 1077)
('서대문', '절도', '검거', 524)
('서대문', '폭력', '발생', 1292)
('서대문', '폭력', '검거', 1029)
('혜화', '살인', '발생', 0)
('혜화', '살인', '검거', 0)
('혜화', '강도', '발생', 3)
('혜화', '강도', '검거', 3)
('혜화', '강간,추행', '발생', 77)
('혜화', '강간,추행', '검거', 53)
('혜화', '절도', '발생', 581)
('혜화', '절도', '검거', 310)
('혜화', '폭력', '발생', 747)
('혜화', '폭력', '검거', 628)
('용산', '살인', '발생', 5)
('용산', '살인', '검거', 3)
('용산', '강도', '발생', 6)
('용산', '강도', '검거', 6)
('용산', '강간,추행', '발생', 230)
('용산', '강간,추행', '검거', 186)
('용산', '절도', '발생', 1111)
('용산', '절도', '검거', 534)
('용산', '폭력', '발생', 1617)
('용산', '폭력', '검거', 1327)
('성북', '살인', '발생', 0)
('성북', '살인', '검거', 0)
('성북', '강도', '발생', 2)
('성북', '강도', '검거', 2)
('성북', '강간', '발생', 95)
('성북', '강간', '검거', 77)
('성북', '절도', '발생', 439)
('성북', '절도', '검거', 233)
('성북', '폭력', '발생', 672)
('성북', '폭력', '검거', 610)
('동대문', '살인', '발생', 10)
('동대문', '살인', '검거', 8)
('동대문', '강도', '발생', 6)
('동대문', '강도', '검거', 5)
('동대문', '강간,추행', '발생', 161)
('동대문', '강간,추행', '검거', 142)
('동대문', '절도', '발생', 1440)
('동대문', '절도', '검거', 713)
('동대문', '폭력', '발생', 1784)
('동대문', '폭력', '검거', 1597)
('마포', '살인', '발생', 9)
('마포', '살인', '검거', 8)
('마포', '강도', '발생', 4)
('마포', '강도', '검거', 3)
('마포', '강간,추행', '발생', 348)
('마포', '강간,추행', '검거', 287)
('마포', '절도', '발생', 1483)
('마포', '절도', '검거', 679)
('마포', '폭력', '발생', 1844)
('마포', '폭력', '검거', 1557)
('영등포', '살인', '발생', 7)
('영등포', '살인', '검거', 4)
('영등포', '강도', '발생', 6)
('영등포', '강도', '검거', 5)
('영등포', '강간,추행', '발생', 315)
('영등포', '강간,추행', '검거', 252)
('영등포', '절도', '발생', 2188)
('영등포', '절도', '검거', 953)
('영등포', '폭력', '발생', 2701)
('영등포', '폭력', '검거', 2157)
('성동', '살인', '발생', 5)
('성동', '살인', '검거', 5)
('성동', '강도', '발생', 3)
('성동', '강도', '검거', 3)
('성동', '강간,추행', '발생', 115)
('성동', '강간,추행', '검거', 98)
('성동', '절도', '발생', 1016)
('성동', '절도', '검거', 565)
('성동', '폭력', '발생', 1223)
('성동', '폭력', '검거', 1103)
('동작', '살인', '발생', 1)
('동작', '살인', '검거', 1)
('동작', '강도', '발생', 1)
('동작', '강도', '검거', 2)
('동작', '강간,추행', '발생', 226)
('동작', '강간,추행', '검거', 121)
('동작', '절도', '발생', 1341)
('동작', '절도', '검거', 592)
('동작', '폭력', '발생', 1631)
('동작', '폭력', '검거', 1370)
('광진', '살인', '발생', 2)
('광진', '살인', '검거', 2)
('광진', '강도', '발생', 4)
('광진', '강도', '검거', 4)
('광진', '강간,추행', '발생', 255)
('광진', '강간,추행', '검거', 224)
('광진', '절도', '발생', 1664)
('광진', '절도', '검거', 874)
('광진', '폭력', '발생', 1676)
('광진', '폭력', '검거', 1407)
('서부', '살인', '발생', 3)
('서부', '살인', '검거', 3)
('서부', '강도', '발생', 3)
('서부', '강도', '검거', 2)
('서부', '강간,추행', '발생', 76)
('서부', '강간,추행', '검거', 71)
('서부', '절도', '발생', 532)
('서부', '절도', '검거', 322)
('서부', '폭력', '발생', 748)
('서부', '폭력', '검거', 667)
('강북', '살인', '발생', 9)
('강북', '살인', '검거', 8)
('강북', '강도', '발생', 5)
('강북', '강도', '검거', 4)
('강북', '강간,추행', '발생', 159)
('강북', '강간,추행', '검거', 132)
('강북', '절도', '발생', 780)
('강북', '절도', '검거', 490)
('강북', '폭력', '발생', 1817)
('강북', '폭력', '검거', 1625)
('금천', '살인', '발생', 4)
('금천', '살인', '검거', 4)
('금천', '강도', '발생', 7)
('금천', '강도', '검거', 6)
('금천', '강간,추행', '발생', 117)
('금천', '강간,추행', '검거', 93)
('금천', '절도', '발생', 999)
('금천', '절도', '검거', 553)
('금천', '폭력', '발생', 1471)
('금천', '폭력', '검거', 1310)
('중랑', '살인', '발생', 10)
('중랑', '살인', '검거', 9)
('중랑', '강도', '발생', 5)
('중랑', '강도', '검거', 6)
('중랑', '강간,추행', '발생', 183)
('중랑', '강간,추행', '검거', 153)
('중랑', '절도', '발생', 1506)
('중랑', '절도', '검거', 889)
('중랑', '폭력', '발생', 2022)
('중랑', '폭력', '검거', 1724)
('강남', '살인', '발생', 5)
('강남', '살인', '검거', 3)
('강남', '강도', '발생', 12)
('강남', '강도', '검거', 10)
('강남', '강간,추행', '발생', 513)
('강남', '강간,추행', '검거', 433)
('강남', '절도', '발생', 1941)
('강남', '절도', '검거', 1016)
('강남', '폭력', '발생', 2283)
('강남', '폭력', '검거', 1911)
('관악', '살인', '발생', 12)
('관악', '살인', '검거', 12)
('관악', '강도', '발생', 3)
('관악', '강도', '검거', 3)
('관악', '강간,추행', '발생', 403)
('관악', '강간,추행', '검거', 351)
('관악', '절도', '발생', 2229)
('관악', '절도', '검거', 1137)
('관악', '폭력', '발생', 2614)
('관악', '폭력', '검거', 2355)
('강서', '살인', '발생', 10)
('강서', '살인', '검거', 9)
('강서', '강도', '발생', 6)
('강서', '강도', '검거', 5)
('강서', '강간,추행', '발생', 265)
('강서', '강간,추행', '검거', 222)
('강서', '절도', '발생', 1689)
('강서', '절도', '검거', 1070)
('강서', '폭력', '발생', 2445)
('강서', '폭력', '검거', 2087)
('강동', '살인', '발생', 3)
('강동', '살인', '검거', 3)
('강동', '강도', '발생', 15)
('강동', '강도', '검거', 14)
('강동', '강간,추행', '발생', 188)
('강동', '강간,추행', '검거', 167)
('강동', '절도', '발생', 1640)
('강동', '절도', '검거', 781)
('강동', '폭력', '발생', 1942)
('강동', '폭력', '검거', 1697)
('종암', '살인', '발생', 4)
('종암', '살인', '검거', 4)
('종암', '강도', '발생', 1)
('종암', '강도', '검거', 0)
('종암', '강간', '발생', 47)
('종암', '강간', '검거', 44)
('종암', '절도', '발생', 549)
('종암', '절도', '검거', 347)
('종암', '폭력', '발생', 758)
('종암', '폭력', '검거', 630)
('구로', '살인', '발생', 6)
('구로', '살인', '검거', 6)
('구로', '강도', '발생', 5)
('구로', '강도', '검거', 5)
('구로', '강간,추행', '발생', 197)
('구로', '강간,추행', '검거', 142)
('구로', '절도', '발생', 1763)
('구로', '절도', '검거', 1008)
('구로', '폭력', '발생', 2204)
('구로', '폭력', '검거', 1823)
('서초', '살인', '발생', 4)
('서초', '살인', '검거', 4)
('서초', '강도', '발생', 5)
('서초', '강도', '검거', 3)
('서초', '강간,추행', '발생', 333)
('서초', '강간,추행', '검거', 253)
('서초', '절도', '발생', 1673)
('서초', '절도', '검거', 801)
('서초', '폭력', '발생', 1750)
('서초', '폭력', '검거', 1415)
('양천', '살인', '발생', 5)
('양천', '살인', '검거', 5)
('양천', '강도', '발생', 3)
('양천', '강도', '검거', 3)
('양천', '강간', '발생', 109)
('양천', '강간', '검거', 90)
('양천', '절도', '발생', 1517)
('양천', '절도', '검거', 718)
('양천', '폭력', '발생', 1582)
('양천', '폭력', '검거', 1270)
('송파', '살인', '발생', 6)
('송파', '살인', '검거', 6)
('송파', '강도', '발생', 13)
('송파', '강도', '검거', 17)
('송파', '강간,추행', '발생', 287)
('송파', '강간,추행', '검거', 235)
('송파', '절도', '발생', 2429)
('송파', '절도', '검거', 1006)
('송파', '폭력', '발생', 2675)
('송파', '폭력', '검거', 2280)
('노원', '살인', '발생', 4)
('노원', '살인', '검거', 3)
('노원', '강도', '발생', 3)
('노원', '강도', '검거', 3)
('노원', '강간,추행', '발생', 169)
('노원', '강간,추행', '검거', 148)
('노원', '절도', '발생', 1404)
('노원', '절도', '검거', 646)
('노원', '폭력', '발생', 2163)
('노원', '폭력', '검거', 1781)
('방배', '살인', '발생', 1)
('방배', '살인', '검거', 1)
('방배', '강도', '발생', 1)
('방배', '강도', '검거', 1)
('방배', '강간', '발생', 63)
('방배', '강간', '검거', 50)
('방배', '절도', '발생', 348)
('방배', '절도', '검거', 159)
('방배', '폭력', '발생', 423)
('방배', '폭력', '검거', 365)
('은평', '살인', '발생', 1)
('은평', '살인', '검거', 1)
('은평', '강도', '발생', 1)
('은평', '강도', '검거', 1)
('은평', '강간,추행', '발생', 95)
('은평', '강간,추행', '검거', 74)
('은평', '절도', '발생', 839)
('은평', '절도', '검거', 434)
('은평', '폭력', '발생', 1092)
('은평', '폭력', '검거', 956)
('도봉', '살인', '발생', 0)
('도봉', '살인', '검거', 0)
('도봉', '강도', '발생', 2)
('도봉', '강도', '검거', 2)
('도봉', '강간', '발생', 82)
('도봉', '강간', '검거', 87)
('도봉', '절도', '발생', 861)
('도봉', '절도', '검거', 379)
('도봉', '폭력', '발생', 1234)
('도봉', '폭력', '검거', 1022)
('수서', '살인', '발생', 1)
('수서', '살인', '검거', 2)
('수서', '강도', '발생', 2)
('수서', '강도', '검거', 1)
('수서', '강간,추행', '발생', 195)
('수서', '강간,추행', '검거', 194)
('수서', '절도', '발생', 1010)
('수서', '절도', '검거', 475)
('수서', '폭력', '발생', 1394)
('수서', '폭력', '검거', 1200)

In [34]:
cursor.execute("select * from crime_status")

result = cursor.fetchall()
for row in result:
    print(row)

(2020, '중부', '살인', '발생', 1)
(2020, '중부', '살인', '검거', 1)
(2020, '중부', '강도', '발생', 3)
(2020, '중부', '강도', '검거', 4)
(2020, '중부', '강간,추행', '발생', 113)
(2020, '중부', '강간,추행', '검거', 76)
(2020, '중부', '절도', '발생', 943)
(2020, '중부', '절도', '검거', 495)
(2020, '중부', '폭력', '발생', 997)
(2020, '중부', '폭력', '검거', 830)
(2020, '종로', '살인', '발생', 9)
(2020, '종로', '살인', '검거', 6)
(2020, '종로', '강도', '발생', 4)
(2020, '종로', '강도', '검거', 4)
(2020, '종로', '강간,추행', '발생', 115)
(2020, '종로', '강간,추행', '검거', 93)
(2020, '종로', '절도', '발생', 602)
(2020, '종로', '절도', '검거', 284)
(2020, '종로', '폭력', '발생', 964)
(2020, '종로', '폭력', '검거', 792)
(2020, '남대문', '살인', '발생', 1)
(2020, '남대문', '살인', '검거', 1)
(2020, '남대문', '강도', '발생', 2)
(2020, '남대문', '강도', '검거', 2)
(2020, '남대문', '강간,추행', '발생', 73)
(2020, '남대문', '강간,추행', '검거', 52)
(2020, '남대문', '절도', '발생', 699)
(2020, '남대문', '절도', '검거', 368)
(2020, '남대문', '폭력', '발생', 579)
(2020, '남대문', '폭력', '검거', 494)
(2020, '서대문', '살인', '발생', 3)
(2020, '서대문', '살인', '검거', 3)
(2020, '서대문', '강도', '발생', 2)
(2020, '서대문', '강도', '검거', 1)
(2020, '서대문', '강간,추행', '발생', 159)
(2020, '서대문', '강간,추행', '검거', 149)
(2020, '서대문', '절도', '발생', 1077)
(2020, '서대문', '절도', '검거', 524)
(2020, '서대문', '폭력', '발생', 1292)
(2020, '서대문', '폭력', '검거', 1029)
(2020, '혜화', '살인', '발생', 0)
(2020, '혜화', '살인', '검거', 0)
(2020, '혜화', '강도', '발생', 3)
(2020, '혜화', '강도', '검거', 3)
(2020, '혜화', '강간,추행', '발생', 77)
(2020, '혜화', '강간,추행', '검거', 53)
(2020, '혜화', '절도', '발생', 581)
(2020, '혜화', '절도', '검거', 310)
(2020, '혜화', '폭력', '발생', 747)
(2020, '혜화', '폭력', '검거', 628)
(2020, '용산', '살인', '발생', 5)
(2020, '용산', '살인', '검거', 3)
(2020, '용산', '강도', '발생', 6)
(2020, '용산', '강도', '검거', 6)
(2020, '용산', '강간,추행', '발생', 230)
(2020, '용산', '강간,추행', '검거', 186)
(2020, '용산', '절도', '발생', 1111)
(2020, '용산', '절도', '검거', 534)
(2020, '용산', '폭력', '발생', 1617)
(2020, '용산', '폭력', '검거', 1327)
(2020, '성북', '살인', '발생', 0)
(2020, '성북', '살인', '검거', 0)
(2020, '성북', '강도', '발생', 2)
(2020, '성북', '강도', '검거', 2)
(2020, '성북', '강간', '발생', 95)
(2020, '성북', '강간', '검거', 77)
(2020, '성북', '절도', '발생', 439)
(2020, '성북', '절도', '검거', 233)
(2020, '성북', '폭력', '발생', 672)
(2020, '성북', '폭력', '검거', 610)
(2020, '동대문', '살인', '발생', 10)
(2020, '동대문', '살인', '검거', 8)
(2020, '동대문', '강도', '발생', 6)
(2020, '동대문', '강도', '검거', 5)
(2020, '동대문', '강간,추행', '발생', 161)
(2020, '동대문', '강간,추행', '검거', 142)
(2020, '동대문', '절도', '발생', 1440)
(2020, '동대문', '절도', '검거', 713)
(2020, '동대문', '폭력', '발생', 1784)
(2020, '동대문', '폭력', '검거', 1597)
(2020, '마포', '살인', '발생', 9)
(2020, '마포', '살인', '검거', 8)
(2020, '마포', '강도', '발생', 4)
(2020, '마포', '강도', '검거', 3)
(2020, '마포', '강간,추행', '발생', 348)
(2020, '마포', '강간,추행', '검거', 287)
(2020, '마포', '절도', '발생', 1483)
(2020, '마포', '절도', '검거', 679)
(2020, '마포', '폭력', '발생', 1844)
(2020, '마포', '폭력', '검거', 1557)
(2020, '영등포', '살인', '발생', 7)
(2020, '영등포', '살인', '검거', 4)
(2020, '영등포', '강도', '발생', 6)
(2020, '영등포', '강도', '검거', 5)
(2020, '영등포', '강간,추행', '발생', 315)
(2020, '영등포', '강간,추행', '검거', 252)
(2020, '영등포', '절도', '발생', 2188)
(2020, '영등포', '절도', '검거', 953)
(2020, '영등포', '폭력', '발생', 2701)
(2020, '영등포', '폭력', '검거', 2157)
(2020, '성동', '살인', '발생', 5)
(2020, '성동', '살인', '검거', 5)
(2020, '성동', '강도', '발생', 3)
(2020, '성동', '강도', '검거', 3)
(2020, '성동', '강간,추행', '발생', 115)
(2020, '성동', '강간,추행', '검거', 98)
(2020, '성동', '절도', '발생', 1016)
(2020, '성동', '절도', '검거', 565)
(2020, '성동', '폭력', '발생', 1223)
(2020, '성동', '폭력', '검거', 1103)
(2020, '동작', '살인', '발생', 1)
(2020, '동작', '살인', '검거', 1)
(2020, '동작', '강도', '발생', 1)
(2020, '동작', '강도', '검거', 2)
(2020, '동작', '강간,추행', '발생', 226)
(2020, '동작', '강간,추행', '검거', 121)
(2020, '동작', '절도', '발생', 1341)
(2020, '동작', '절도', '검거', 592)
(2020, '동작', '폭력', '발생', 1631)
(2020, '동작', '폭력', '검거', 1370)
(2020, '광진', '살인', '발생', 2)
(2020, '광진', '살인', '검거', 2)
(2020, '광진', '강도', '발생', 4)
(2020, '광진', '강도', '검거', 4)
(2020, '광진', '강간,추행', '발생', 255)
(2020, '광진', '강간,추행', '검거', 224)
(2020, '광진', '절도', '발생', 1664)
(2020, '광진', '절도', '검거', 874)
(2020, '광진', '폭력', '발생', 1676)
(2020, '광진', '폭력', '검거', 1407)
(2020, '서부', '살인', '발생', 3)
(2020, '서부', '살인', '검거', 3)
(2020, '서부', '강도', '발생', 3)
(2020, '서부', '강도', '검거', 2)
(2020, '서부', '강간,추행', '발생', 76)
(2020, '서부', '강간,추행', '검거', 71)
(2020, '서부', '절도', '발생', 532)
(2020, '서부', '절도', '검거', 322)
(2020, '서부', '폭력', '발생', 748)
(2020, '서부', '폭력', '검거', 667)
(2020, '강북', '살인', '발생', 9)
(2020, '강북', '살인', '검거', 8)
(2020, '강북', '강도', '발생', 5)
(2020, '강북', '강도', '검거', 4)
(2020, '강북', '강간,추행', '발생', 159)
(2020, '강북', '강간,추행', '검거', 132)
(2020, '강북', '절도', '발생', 780)
(2020, '강북', '절도', '검거', 490)
(2020, '강북', '폭력', '발생', 1817)
(2020, '강북', '폭력', '검거', 1625)
(2020, '금천', '살인', '발생', 4)
(2020, '금천', '살인', '검거', 4)
(2020, '금천', '강도', '발생', 7)
(2020, '금천', '강도', '검거', 6)
(2020, '금천', '강간,추행', '발생', 117)
(2020, '금천', '강간,추행', '검거', 93)
(2020, '금천', '절도', '발생', 999)
(2020, '금천', '절도', '검거', 553)
(2020, '금천', '폭력', '발생', 1471)
(2020, '금천', '폭력', '검거', 1310)
(2020, '중랑', '살인', '발생', 10)
(2020, '중랑', '살인', '검거', 9)
(2020, '중랑', '강도', '발생', 5)
(2020, '중랑', '강도', '검거', 6)
(2020, '중랑', '강간,추행', '발생', 183)
(2020, '중랑', '강간,추행', '검거', 153)
(2020, '중랑', '절도', '발생', 1506)
(2020, '중랑', '절도', '검거', 889)
(2020, '중랑', '폭력', '발생', 2022)
(2020, '중랑', '폭력', '검거', 1724)
(2020, '강남', '살인', '발생', 5)
(2020, '강남', '살인', '검거', 3)
(2020, '강남', '강도', '발생', 12)
(2020, '강남', '강도', '검거', 10)
(2020, '강남', '강간,추행', '발생', 513)
(2020, '강남', '강간,추행', '검거', 433)
(2020, '강남', '절도', '발생', 1941)
(2020, '강남', '절도', '검거', 1016)
(2020, '강남', '폭력', '발생', 2283)
(2020, '강남', '폭력', '검거', 1911)
(2020, '관악', '살인', '발생', 12)
(2020, '관악', '살인', '검거', 12)
(2020, '관악', '강도', '발생', 3)
(2020, '관악', '강도', '검거', 3)
(2020, '관악', '강간,추행', '발생', 403)
(2020, '관악', '강간,추행', '검거', 351)
(2020, '관악', '절도', '발생', 2229)
(2020, '관악', '절도', '검거', 1137)
(2020, '관악', '폭력', '발생', 2614)
(2020, '관악', '폭력', '검거', 2355)
(2020, '강서', '살인', '발생', 10)
(2020, '강서', '살인', '검거', 9)
(2020, '강서', '강도', '발생', 6)
(2020, '강서', '강도', '검거', 5)
(2020, '강서', '강간,추행', '발생', 265)
(2020, '강서', '강간,추행', '검거', 222)
(2020, '강서', '절도', '발생', 1689)
(2020, '강서', '절도', '검거', 1070)
(2020, '강서', '폭력', '발생', 2445)
(2020, '강서', '폭력', '검거', 2087)
(2020, '강동', '살인', '발생', 3)
(2020, '강동', '살인', '검거', 3)
(2020, '강동', '강도', '발생', 15)
(2020, '강동', '강도', '검거', 14)
(2020, '강동', '강간,추행', '발생', 188)
(2020, '강동', '강간,추행', '검거', 167)
(2020, '강동', '절도', '발생', 1640)
(2020, '강동', '절도', '검거', 781)
(2020, '강동', '폭력', '발생', 1942)
(2020, '강동', '폭력', '검거', 1697)
(2020, '종암', '살인', '발생', 4)
(2020, '종암', '살인', '검거', 4)
(2020, '종암', '강도', '발생', 1)
(2020, '종암', '강도', '검거', 0)
(2020, '종암', '강간', '발생', 47)
(2020, '종암', '강간', '검거', 44)
(2020, '종암', '절도', '발생', 549)
(2020, '종암', '절도', '검거', 347)
(2020, '종암', '폭력', '발생', 758)
(2020, '종암', '폭력', '검거', 630)
(2020, '구로', '살인', '발생', 6)
(2020, '구로', '살인', '검거', 6)
(2020, '구로', '강도', '발생', 5)
(2020, '구로', '강도', '검거', 5)
(2020, '구로', '강간,추행', '발생', 197)
(2020, '구로', '강간,추행', '검거', 142)
(2020, '구로', '절도', '발생', 1763)
(2020, '구로', '절도', '검거', 1008)
(2020, '구로', '폭력', '발생', 2204)
(2020, '구로', '폭력', '검거', 1823)
(2020, '서초', '살인', '발생', 4)
(2020, '서초', '살인', '검거', 4)
(2020, '서초', '강도', '발생', 5)
(2020, '서초', '강도', '검거', 3)
(2020, '서초', '강간,추행', '발생', 333)
(2020, '서초', '강간,추행', '검거', 253)
(2020, '서초', '절도', '발생', 1673)
(2020, '서초', '절도', '검거', 801)
(2020, '서초', '폭력', '발생', 1750)
(2020, '서초', '폭력', '검거', 1415)
(2020, '양천', '살인', '발생', 5)
(2020, '양천', '살인', '검거', 5)
(2020, '양천', '강도', '발생', 3)
(2020, '양천', '강도', '검거', 3)
(2020, '양천', '강간', '발생', 109)
(2020, '양천', '강간', '검거', 90)
(2020, '양천', '절도', '발생', 1517)
(2020, '양천', '절도', '검거', 718)
(2020, '양천', '폭력', '발생', 1582)
(2020, '양천', '폭력', '검거', 1270)
(2020, '송파', '살인', '발생', 6)
(2020, '송파', '살인', '검거', 6)
(2020, '송파', '강도', '발생', 13)
(2020, '송파', '강도', '검거', 17)
(2020, '송파', '강간,추행', '발생', 287)
(2020, '송파', '강간,추행', '검거', 235)
(2020, '송파', '절도', '발생', 2429)
(2020, '송파', '절도', '검거', 1006)
(2020, '송파', '폭력', '발생', 2675)
(2020, '송파', '폭력', '검거', 2280)
(2020, '노원', '살인', '발생', 4)
(2020, '노원', '살인', '검거', 3)
(2020, '노원', '강도', '발생', 3)
(2020, '노원', '강도', '검거', 3)
(2020, '노원', '강간,추행', '발생', 169)
(2020, '노원', '강간,추행', '검거', 148)
(2020, '노원', '절도', '발생', 1404)
(2020, '노원', '절도', '검거', 646)
(2020, '노원', '폭력', '발생', 2163)
(2020, '노원', '폭력', '검거', 1781)
(2020, '방배', '살인', '발생', 1)
(2020, '방배', '살인', '검거', 1)
(2020, '방배', '강도', '발생', 1)
(2020, '방배', '강도', '검거', 1)
(2020, '방배', '강간', '발생', 63)
(2020, '방배', '강간', '검거', 50)
(2020, '방배', '절도', '발생', 348)
(2020, '방배', '절도', '검거', 159)
(2020, '방배', '폭력', '발생', 423)
(2020, '방배', '폭력', '검거', 365)
(2020, '은평', '살인', '발생', 1)
(2020, '은평', '살인', '검거', 1)
(2020, '은평', '강도', '발생', 1)
(2020, '은평', '강도', '검거', 1)
(2020, '은평', '강간,추행', '발생', 95)
(2020, '은평', '강간,추행', '검거', 74)
(2020, '은평', '절도', '발생', 839)
(2020, '은평', '절도', '검거', 434)
(2020, '은평', '폭력', '발생', 1092)
(2020, '은평', '폭력', '검거', 956)
(2020, '도봉', '살인', '발생', 0)
(2020, '도봉', '살인', '검거', 0)
(2020, '도봉', '강도', '발생', 2)
(2020, '도봉', '강도', '검거', 2)
(2020, '도봉', '강간', '발생', 82)
(2020, '도봉', '강간', '검거', 87)
(2020, '도봉', '절도', '발생', 861)
(2020, '도봉', '절도', '검거', 379)
(2020, '도봉', '폭력', '발생', 1234)
(2020, '도봉', '폭력', '검거', 1022)
(2020, '수서', '살인', '발생', 1)
(2020, '수서', '살인', '검거', 2)
(2020, '수서', '강도', '발생', 2)
(2020, '수서', '강도', '검거', 1)
(2020, '수서', '강간,추행', '발생', 195)
(2020, '수서', '강간,추행', '검거', 194)
(2020, '수서', '절도', '발생', 1010)
(2020, '수서', '절도', '검거', 475)
(2020, '수서', '폭력', '발생', 1394)
(2020, '수서', '폭력', '검거', 1200)
(2020, '중부', '살인', '발생', 1)
(2020, '중부', '살인', '검거', 1)
(2020, '중부', '강도', '발생', 3)
(2020, '중부', '강도', '검거', 4)
(2020, '중부', '강간,추행', '발생', 113)
(2020, '중부', '강간,추행', '검거', 76)
(2020, '중부', '절도', '발생', 943)
(2020, '중부', '절도', '검거', 495)
(2020, '중부', '폭력', '발생', 997)
(2020, '중부', '폭력', '검거', 830)
(2020, '종로', '살인', '발생', 9)
(2020, '종로', '살인', '검거', 6)
(2020, '종로', '강도', '발생', 4)
(2020, '종로', '강도', '검거', 4)
(2020, '종로', '강간,추행', '발생', 115)
(2020, '종로', '강간,추행', '검거', 93)
(2020, '종로', '절도', '발생', 602)
(2020, '종로', '절도', '검거', 284)
(2020, '종로', '폭력', '발생', 964)
(2020, '종로', '폭력', '검거', 792)
(2020, '남대문', '살인', '발생', 1)
(2020, '남대문', '살인', '검거', 1)
(2020, '남대문', '강도', '발생', 2)
(2020, '남대문', '강도', '검거', 2)
(2020, '남대문', '강간,추행', '발생', 73)
(2020, '남대문', '강간,추행', '검거', 52)
(2020, '남대문', '절도', '발생', 699)
(2020, '남대문', '절도', '검거', 368)
(2020, '남대문', '폭력', '발생', 579)
(2020, '남대문', '폭력', '검거', 494)
(2020, '서대문', '살인', '발생', 3)
(2020, '서대문', '살인', '검거', 3)
(2020, '서대문', '강도', '발생', 2)
(2020, '서대문', '강도', '검거', 1)
(2020, '서대문', '강간,추행', '발생', 159)
(2020, '서대문', '강간,추행', '검거', 149)
(2020, '서대문', '절도', '발생', 1077)
(2020, '서대문', '절도', '검거', 524)
(2020, '서대문', '폭력', '발생', 1292)
(2020, '서대문', '폭력', '검거', 1029)
(2020, '혜화', '살인', '발생', 0)
(2020, '혜화', '살인', '검거', 0)
(2020, '혜화', '강도', '발생', 3)
(2020, '혜화', '강도', '검거', 3)
(2020, '혜화', '강간,추행', '발생', 77)
(2020, '혜화', '강간,추행', '검거', 53)
(2020, '혜화', '절도', '발생', 581)
(2020, '혜화', '절도', '검거', 310)
(2020, '혜화', '폭력', '발생', 747)
(2020, '혜화', '폭력', '검거', 628)
(2020, '용산', '살인', '발생', 5)
(2020, '용산', '살인', '검거', 3)
(2020, '용산', '강도', '발생', 6)
(2020, '용산', '강도', '검거', 6)
(2020, '용산', '강간,추행', '발생', 230)
(2020, '용산', '강간,추행', '검거', 186)
(2020, '용산', '절도', '발생', 1111)
(2020, '용산', '절도', '검거', 534)
(2020, '용산', '폭력', '발생', 1617)
(2020, '용산', '폭력', '검거', 1327)
(2020, '성북', '살인', '발생', 0)
(2020, '성북', '살인', '검거', 0)
(2020, '성북', '강도', '발생', 2)
(2020, '성북', '강도', '검거', 2)
(2020, '성북', '강간', '발생', 95)
(2020, '성북', '강간', '검거', 77)
(2020, '성북', '절도', '발생', 439)
(2020, '성북', '절도', '검거', 233)
(2020, '성북', '폭력', '발생', 672)
(2020, '성북', '폭력', '검거', 610)
(2020, '동대문', '살인', '발생', 10)
(2020, '동대문', '살인', '검거', 8)
(2020, '동대문', '강도', '발생', 6)
(2020, '동대문', '강도', '검거', 5)
(2020, '동대문', '강간,추행', '발생', 161)
(2020, '동대문', '강간,추행', '검거', 142)
(2020, '동대문', '절도', '발생', 1440)
(2020, '동대문', '절도', '검거', 713)
(2020, '동대문', '폭력', '발생', 1784)
(2020, '동대문', '폭력', '검거', 1597)
(2020, '마포', '살인', '발생', 9)
(2020, '마포', '살인', '검거', 8)
(2020, '마포', '강도', '발생', 4)
(2020, '마포', '강도', '검거', 3)
(2020, '마포', '강간,추행', '발생', 348)
(2020, '마포', '강간,추행', '검거', 287)
(2020, '마포', '절도', '발생', 1483)
(2020, '마포', '절도', '검거', 679)
(2020, '마포', '폭력', '발생', 1844)
(2020, '마포', '폭력', '검거', 1557)
(2020, '영등포', '살인', '발생', 7)
(2020, '영등포', '살인', '검거', 4)
(2020, '영등포', '강도', '발생', 6)
(2020, '영등포', '강도', '검거', 5)
(2020, '영등포', '강간,추행', '발생', 315)
(2020, '영등포', '강간,추행', '검거', 252)
(2020, '영등포', '절도', '발생', 2188)
(2020, '영등포', '절도', '검거', 953)
(2020, '영등포', '폭력', '발생', 2701)
(2020, '영등포', '폭력', '검거', 2157)
(2020, '성동', '살인', '발생', 5)
(2020, '성동', '살인', '검거', 5)
(2020, '성동', '강도', '발생', 3)
(2020, '성동', '강도', '검거', 3)
(2020, '성동', '강간,추행', '발생', 115)
(2020, '성동', '강간,추행', '검거', 98)
(2020, '성동', '절도', '발생', 1016)
(2020, '성동', '절도', '검거', 565)
(2020, '성동', '폭력', '발생', 1223)
(2020, '성동', '폭력', '검거', 1103)
(2020, '동작', '살인', '발생', 1)
(2020, '동작', '살인', '검거', 1)
(2020, '동작', '강도', '발생', 1)
(2020, '동작', '강도', '검거', 2)
(2020, '동작', '강간,추행', '발생', 226)
(2020, '동작', '강간,추행', '검거', 121)
(2020, '동작', '절도', '발생', 1341)
(2020, '동작', '절도', '검거', 592)
(2020, '동작', '폭력', '발생', 1631)
(2020, '동작', '폭력', '검거', 1370)
(2020, '광진', '살인', '발생', 2)
(2020, '광진', '살인', '검거', 2)
(2020, '광진', '강도', '발생', 4)
(2020, '광진', '강도', '검거', 4)
(2020, '광진', '강간,추행', '발생', 255)
(2020, '광진', '강간,추행', '검거', 224)
(2020, '광진', '절도', '발생', 1664)
(2020, '광진', '절도', '검거', 874)
(2020, '광진', '폭력', '발생', 1676)
(2020, '광진', '폭력', '검거', 1407)
(2020, '서부', '살인', '발생', 3)
(2020, '서부', '살인', '검거', 3)
(2020, '서부', '강도', '발생', 3)
(2020, '서부', '강도', '검거', 2)
(2020, '서부', '강간,추행', '발생', 76)
(2020, '서부', '강간,추행', '검거', 71)
(2020, '서부', '절도', '발생', 532)
(2020, '서부', '절도', '검거', 322)
(2020, '서부', '폭력', '발생', 748)
(2020, '서부', '폭력', '검거', 667)
(2020, '강북', '살인', '발생', 9)
(2020, '강북', '살인', '검거', 8)
(2020, '강북', '강도', '발생', 5)
(2020, '강북', '강도', '검거', 4)
(2020, '강북', '강간,추행', '발생', 159)
(2020, '강북', '강간,추행', '검거', 132)
(2020, '강북', '절도', '발생', 780)
(2020, '강북', '절도', '검거', 490)
(2020, '강북', '폭력', '발생', 1817)
(2020, '강북', '폭력', '검거', 1625)
(2020, '금천', '살인', '발생', 4)
(2020, '금천', '살인', '검거', 4)
(2020, '금천', '강도', '발생', 7)
(2020, '금천', '강도', '검거', 6)
(2020, '금천', '강간,추행', '발생', 117)
(2020, '금천', '강간,추행', '검거', 93)
(2020, '금천', '절도', '발생', 999)
(2020, '금천', '절도', '검거', 553)
(2020, '금천', '폭력', '발생', 1471)
(2020, '금천', '폭력', '검거', 1310)
(2020, '중랑', '살인', '발생', 10)
(2020, '중랑', '살인', '검거', 9)
(2020, '중랑', '강도', '발생', 5)
(2020, '중랑', '강도', '검거', 6)
(2020, '중랑', '강간,추행', '발생', 183)
(2020, '중랑', '강간,추행', '검거', 153)
(2020, '중랑', '절도', '발생', 1506)
(2020, '중랑', '절도', '검거', 889)
(2020, '중랑', '폭력', '발생', 2022)
(2020, '중랑', '폭력', '검거', 1724)
(2020, '강남', '살인', '발생', 5)
(2020, '강남', '살인', '검거', 3)
(2020, '강남', '강도', '발생', 12)
(2020, '강남', '강도', '검거', 10)
(2020, '강남', '강간,추행', '발생', 513)
(2020, '강남', '강간,추행', '검거', 433)
(2020, '강남', '절도', '발생', 1941)
(2020, '강남', '절도', '검거', 1016)
(2020, '강남', '폭력', '발생', 2283)
(2020, '강남', '폭력', '검거', 1911)
(2020, '관악', '살인', '발생', 12)
(2020, '관악', '살인', '검거', 12)
(2020, '관악', '강도', '발생', 3)
(2020, '관악', '강도', '검거', 3)
(2020, '관악', '강간,추행', '발생', 403)
(2020, '관악', '강간,추행', '검거', 351)
(2020, '관악', '절도', '발생', 2229)
(2020, '관악', '절도', '검거', 1137)
(2020, '관악', '폭력', '발생', 2614)
(2020, '관악', '폭력', '검거', 2355)
(2020, '강서', '살인', '발생', 10)
(2020, '강서', '살인', '검거', 9)
(2020, '강서', '강도', '발생', 6)
(2020, '강서', '강도', '검거', 5)
(2020, '강서', '강간,추행', '발생', 265)
(2020, '강서', '강간,추행', '검거', 222)
(2020, '강서', '절도', '발생', 1689)
(2020, '강서', '절도', '검거', 1070)
(2020, '강서', '폭력', '발생', 2445)
(2020, '강서', '폭력', '검거', 2087)
(2020, '강동', '살인', '발생', 3)
(2020, '강동', '살인', '검거', 3)
(2020, '강동', '강도', '발생', 15)
(2020, '강동', '강도', '검거', 14)
(2020, '강동', '강간,추행', '발생', 188)
(2020, '강동', '강간,추행', '검거', 167)
(2020, '강동', '절도', '발생', 1640)
(2020, '강동', '절도', '검거', 781)
(2020, '강동', '폭력', '발생', 1942)
(2020, '강동', '폭력', '검거', 1697)
(2020, '종암', '살인', '발생', 4)
(2020, '종암', '살인', '검거', 4)
(2020, '종암', '강도', '발생', 1)
(2020, '종암', '강도', '검거', 0)
(2020, '종암', '강간', '발생', 47)
(2020, '종암', '강간', '검거', 44)
(2020, '종암', '절도', '발생', 549)
(2020, '종암', '절도', '검거', 347)
(2020, '종암', '폭력', '발생', 758)
(2020, '종암', '폭력', '검거', 630)
(2020, '구로', '살인', '발생', 6)
(2020, '구로', '살인', '검거', 6)
(2020, '구로', '강도', '발생', 5)
(2020, '구로', '강도', '검거', 5)
(2020, '구로', '강간,추행', '발생', 197)
(2020, '구로', '강간,추행', '검거', 142)
(2020, '구로', '절도', '발생', 1763)
(2020, '구로', '절도', '검거', 1008)
(2020, '구로', '폭력', '발생', 2204)
(2020, '구로', '폭력', '검거', 1823)
(2020, '서초', '살인', '발생', 4)
(2020, '서초', '살인', '검거', 4)
(2020, '서초', '강도', '발생', 5)
(2020, '서초', '강도', '검거', 3)
(2020, '서초', '강간,추행', '발생', 333)
(2020, '서초', '강간,추행', '검거', 253)
(2020, '서초', '절도', '발생', 1673)
(2020, '서초', '절도', '검거', 801)
(2020, '서초', '폭력', '발생', 1750)
(2020, '서초', '폭력', '검거', 1415)
(2020, '양천', '살인', '발생', 5)
(2020, '양천', '살인', '검거', 5)
(2020, '양천', '강도', '발생', 3)
(2020, '양천', '강도', '검거', 3)
(2020, '양천', '강간', '발생', 109)
(2020, '양천', '강간', '검거', 90)
(2020, '양천', '절도', '발생', 1517)
(2020, '양천', '절도', '검거', 718)
(2020, '양천', '폭력', '발생', 1582)
(2020, '양천', '폭력', '검거', 1270)
(2020, '송파', '살인', '발생', 6)
(2020, '송파', '살인', '검거', 6)
(2020, '송파', '강도', '발생', 13)
(2020, '송파', '강도', '검거', 17)
(2020, '송파', '강간,추행', '발생', 287)
(2020, '송파', '강간,추행', '검거', 235)
(2020, '송파', '절도', '발생', 2429)
(2020, '송파', '절도', '검거', 1006)
(2020, '송파', '폭력', '발생', 2675)
(2020, '송파', '폭력', '검거', 2280)
(2020, '노원', '살인', '발생', 4)
(2020, '노원', '살인', '검거', 3)
(2020, '노원', '강도', '발생', 3)
(2020, '노원', '강도', '검거', 3)
(2020, '노원', '강간,추행', '발생', 169)
(2020, '노원', '강간,추행', '검거', 148)
(2020, '노원', '절도', '발생', 1404)
(2020, '노원', '절도', '검거', 646)
(2020, '노원', '폭력', '발생', 2163)
(2020, '노원', '폭력', '검거', 1781)
(2020, '방배', '살인', '발생', 1)
(2020, '방배', '살인', '검거', 1)
(2020, '방배', '강도', '발생', 1)
(2020, '방배', '강도', '검거', 1)
(2020, '방배', '강간', '발생', 63)
(2020, '방배', '강간', '검거', 50)
(2020, '방배', '절도', '발생', 348)
(2020, '방배', '절도', '검거', 159)
(2020, '방배', '폭력', '발생', 423)
(2020, '방배', '폭력', '검거', 365)
(2020, '은평', '살인', '발생', 1)
(2020, '은평', '살인', '검거', 1)
(2020, '은평', '강도', '발생', 1)
(2020, '은평', '강도', '검거', 1)
(2020, '은평', '강간,추행', '발생', 95)
(2020, '은평', '강간,추행', '검거', 74)
(2020, '은평', '절도', '발생', 839)
(2020, '은평', '절도', '검거', 434)
(2020, '은평', '폭력', '발생', 1092)
(2020, '은평', '폭력', '검거', 956)
(2020, '도봉', '살인', '발생', 0)
(2020, '도봉', '살인', '검거', 0)
(2020, '도봉', '강도', '발생', 2)
(2020, '도봉', '강도', '검거', 2)
(2020, '도봉', '강간', '발생', 82)
(2020, '도봉', '강간', '검거', 87)
(2020, '도봉', '절도', '발생', 861)
(2020, '도봉', '절도', '검거', 379)
(2020, '도봉', '폭력', '발생', 1234)
(2020, '도봉', '폭력', '검거', 1022)
(2020, '수서', '살인', '발생', 1)
(2020, '수서', '살인', '검거', 2)
(2020, '수서', '강도', '발생', 2)
(2020, '수서', '강도', '검거', 1)
(2020, '수서', '강간,추행', '발생', 195)
(2020, '수서', '강간,추행', '검거', 194)
(2020, '수서', '절도', '발생', 1010)
(2020, '수서', '절도', '검거', 475)
(2020, '수서', '폭력', '발생', 1394)
(2020, '수서', '폭력', '검거', 1200)

In [36]:
df = pd.DataFrame(result)
df.head()

      0   1      2   3    4
0  2020  중부     살인  발생    1
1  2020  중부     살인  검거    1
2  2020  중부     강도  발생    3
3  2020  중부     강도  검거    4
4  2020  중부  강간,추행  발생  113

In [37]:
remote = mysql.connector.connect(
    host = 'database-1.cjnz1ulpkijp.ap-southeast-2.rds.amazonaws.com',
    port=3306,
    user='admin',
    password="mooltisue305!",
    database = 'zerobase')

In [38]:
cur = remote.cursor(buffered=True)
cur.execute("select * from crime_status")
result = cur.fetchall()
result

[(2020, '중부', '살인', '발생', 1),
 (2020, '중부', '살인', '검거', 1),
 (2020, '중부', '강도', '발생', 3),
 (2020, '중부', '강도', '검거', 4),
 (2020, '중부', '강간,추행', '발생', 113),
 (2020, '중부', '강간,추행', '검거', 76),
 (2020, '중부', '절도', '발생', 943),
 (2020, '중부', '절도', '검거', 495),
 (2020, '중부', '폭력', '발생', 997),
 (2020, '중부', '폭력', '검거', 830),
 (2020, '종로', '살인', '발생', 9),
 (2020, '종로', '살인', '검거', 6),
 (2020, '종로', '강도', '발생', 4),
 (2020, '종로', '강도', '검거', 4),
 (2020, '종로', '강간,추행', '발생', 115),
 (2020, '종로', '강간,추행', '검거', 93),
 (2020, '종로', '절도', '발생', 602),
 (2020, '종로', '절도', '검거', 284),
 (2020, '종로', '폭력', '발생', 964),
 (2020, '종로', '폭력', '검거', 792),
 (2020, '남대문', '살인', '발생', 1),
 (2020, '남대문', '살인', '검거', 1),
 (2020, '남대문', '강도', '발생', 2),
 (2020, '남대문', '강도', '검거', 2),
 (2020, '남대문', '강간,추행', '발생', 73),
 (2020, '남대문', '강간,추행', '검거', 52),
 (2020, '남대문', '절도', '발생', 699),
 (2020, '남대문', '절도', '검거', 368),
 (2020, '남대문', '폭력', '발생', 579),
 (2020, '남대문', '폭력', '검거', 494),
 (2020, '서대문', '살인', '발생', 3),
 (2020, '서대문', '살인', '검거', 3),
 (2020, '서대문', '강도', '발생', 2),
 (2020, '서대문', '강도', '검거', 1),
 (2020, '서대문', '강간,추행', '발생', 159),
 (2020, '서대문', '강간,추행', '검거', 149),
 (2020, '서대문', '절도', '발생', 1077),
 (2020, '서대문', '절도', '검거', 524),
 (2020, '서대문', '폭력', '발생', 1292),
 (2020, '서대문', '폭력', '검거', 1029),
 (2020, '혜화', '살인', '발생', 0),
 (2020, '혜화', '살인', '검거', 0),
 (2020, '혜화', '강도', '발생', 3),
 (2020, '혜화', '강도', '검거', 3),
 (2020, '혜화', '강간,추행', '발생', 77),
 (2020, '혜화', '강간,추행', '검거', 53),
 (2020, '혜화', '절도', '발생', 581),
 (2020, '혜화', '절도', '검거', 310),
 (2020, '혜화', '폭력', '발생', 747),
 (2020, '혜화', '폭력', '검거', 628),
 (2020, '용산', '살인', '발생', 5),
 (2020, '용산', '살인', '검거', 3),
 (2020, '용산', '강도', '발생', 6),
 (2020, '용산', '강도', '검거', 6),
 (2020, '용산', '강간,추행', '발생', 230),
 (2020, '용산', '강간,추행', '검거', 186),
 (2020, '용산', '절도', '발생', 1111),
 (2020, '용산', '절도', '검거', 534),
 (2020, '용산', '폭력', '발생', 1617),
 (2020, '용산', '폭력', '검거', 1327),
 (2020, '성북', '살인', '발생', 0),
 (2020, '성북', '살인', '검거', 0),
 (2020, '성북', '강도', '발생', 2),
 (2020, '성북', '강도', '검거', 2),
 (2020, '성북', '강간', '발생', 95),
 (2020, '성북', '강간', '검거', 77),
 (2020, '성북', '절도', '발생', 439),
 (2020, '성북', '절도', '검거', 233),
 (2020, '성북', '폭력', '발생', 672),
 (2020, '성북', '폭력', '검거', 610),
 (2020, '동대문', '살인', '발생', 10),
 (2020, '동대문', '살인', '검거', 8),
 (2020, '동대문', '강도', '발생', 6),
 (2020, '동대문', '강도', '검거', 5),
 (2020, '동대문', '강간,추행', '발생', 161),
 (2020, '동대문', '강간,추행', '검거', 142),
 (2020, '동대문', '절도', '발생', 1440),
 (2020, '동대문', '절도', '검거', 713),
 (2020, '동대문', '폭력', '발생', 1784),
 (2020, '동대문', '폭력', '검거', 1597),
 (2020, '마포', '살인', '발생', 9),
 (2020, '마포', '살인', '검거', 8),
 (2020, '마포', '강도', '발생', 4),
 (2020, '마포', '강도', '검거', 3),
 (2020, '마포', '강간,추행', '발생', 348),
 (2020, '마포', '강간,추행', '검거', 287),
 (2020, '마포', '절도', '발생', 1483),
 (2020, '마포', '절도', '검거', 679),
 (2020, '마포', '폭력', '발생', 1844),
 (2020, '마포', '폭력', '검거', 1557),
 (2020, '영등포', '살인', '발생', 7),
 (2020, '영등포', '살인', '검거', 4),
 (2020, '영등포', '강도', '발생', 6),
 (2020, '영등포', '강도', '검거', 5),
 (2020, '영등포', '강간,추행', '발생', 315),
 (2020, '영등포', '강간,추행', '검거', 252),
 (2020, '영등포', '절도', '발생', 2188),
 (2020, '영등포', '절도', '검거', 953),
 (2020, '영등포', '폭력', '발생', 2701),
 (2020, '영등포', '폭력', '검거', 2157),
 (2020, '성동', '살인', '발생', 5),
 (2020, '성동', '살인', '검거', 5),
 (2020, '성동', '강도', '발생', 3),
 (2020, '성동', '강도', '검거', 3),
 (2020, '성동', '강간,추행', '발생', 115),
 (2020, '성동', '강간,추행', '검거', 98),
 (2020, '성동', '절도', '발생', 1016),
 (2020, '성동', '절도', '검거', 565),
 (2020, '성동', '폭력', '발생', 1223),
 (2020, '성동', '폭력', '검거', 1103),
 (2020, '동작', '살인', '발생', 1),
 (2020, '동작', '살인', '검거', 1),
 (2020, '동작', '강도', '발생', 1),
 (2020, '동작', '강도', '검거', 2),
 (2020, '동작', '강간,추행', '발생', 226),
 (2020, '동작', '강간,추행', '검거', 121),
 (2020, '동작', '절도', '발생', 1341),
 (2020, '동작', '절도', '검거', 592),
 (2020, '동작', '폭력', '발생', 1631),
 (2020, '동작', '폭력', '검거', 1370),
 (2020, '광진', '살인', '발생', 2),
 (2020, '광진', '살인', '검거', 2),
 (2020, '광진', '강도', '발생', 4),
 (2020, '광진', '강도', '검거', 4),
 (2020, '광진', '강간,추행', '발생', 255),
 (2020, '광진', '강간,추행', '검거', 224),
 (2020, '광진', '절도', '발생', 1664),
 (2020, '광진', '절도', '검거', 874),
 (2020, '광진', '폭력', '발생', 1676),
 (2020, '광진', '폭력', '검거', 1407),
 (2020, '서부', '살인', '발생', 3),
 (2020, '서부', '살인', '검거', 3),
 (2020, '서부', '강도', '발생', 3),
 (2020, '서부', '강도', '검거', 2),
 (2020, '서부', '강간,추행', '발생', 76),
 (2020, '서부', '강간,추행', '검거', 71),
 (2020, '서부', '절도', '발생', 532),
 (2020, '서부', '절도', '검거', 322),
 (2020, '서부', '폭력', '발생', 748),
 (2020, '서부', '폭력', '검거', 667),
 (2020, '강북', '살인', '발생', 9),
 (2020, '강북', '살인', '검거', 8),
 (2020, '강북', '강도', '발생', 5),
 (2020, '강북', '강도', '검거', 4),
 (2020, '강북', '강간,추행', '발생', 159),
 (2020, '강북', '강간,추행', '검거', 132),
 (2020, '강북', '절도', '발생', 780),
 (2020, '강북', '절도', '검거', 490),
 (2020, '강북', '폭력', '발생', 1817),
 (2020, '강북', '폭력', '검거', 1625),
 (2020, '금천', '살인', '발생', 4),
 (2020, '금천', '살인', '검거', 4),
 (2020, '금천', '강도', '발생', 7),
 (2020, '금천', '강도', '검거', 6),
 (2020, '금천', '강간,추행', '발생', 117),
 (2020, '금천', '강간,추행', '검거', 93),
 (2020, '금천', '절도', '발생', 999),
 (2020, '금천', '절도', '검거', 553),
 (2020, '금천', '폭력', '발생', 1471),
 (2020, '금천', '폭력', '검거', 1310),
 (2020, '중랑', '살인', '발생', 10),
 (2020, '중랑', '살인', '검거', 9),
 (2020, '중랑', '강도', '발생', 5),
 (2020, '중랑', '강도', '검거', 6),
 (2020, '중랑', '강간,추행', '발생', 183),
 (2020, '중랑', '강간,추행', '검거', 153),
 (2020, '중랑', '절도', '발생', 1506),
 (2020, '중랑', '절도', '검거', 889),
 (2020, '중랑', '폭력', '발생', 2022),
 (2020, '중랑', '폭력', '검거', 1724),
 (2020, '강남', '살인', '발생', 5),
 (2020, '강남', '살인', '검거', 3),
 (2020, '강남', '강도', '발생', 12),
 (2020, '강남', '강도', '검거', 10),
 (2020, '강남', '강간,추행', '발생', 513),
 (2020, '강남', '강간,추행', '검거', 433),
 (2020, '강남', '절도', '발생', 1941),
 (2020, '강남', '절도', '검거', 1016),
 (2020, '강남', '폭력', '발생', 2283),
 (2020, '강남', '폭력', '검거', 1911),
 (2020, '관악', '살인', '발생', 12),
 (2020, '관악', '살인', '검거', 12),
 (2020, '관악', '강도', '발생', 3),
 (2020, '관악', '강도', '검거', 3),
 (2020, '관악', '강간,추행', '발생', 403),
 (2020, '관악', '강간,추행', '검거', 351),
 (2020, '관악', '절도', '발생', 2229),
 (2020, '관악', '절도', '검거', 1137),
 (2020, '관악', '폭력', '발생', 2614),
 (2020, '관악', '폭력', '검거', 2355),
 (2020, '강서', '살인', '발생', 10),
 (2020, '강서', '살인', '검거', 9),
 (2020, '강서', '강도', '발생', 6),
 (2020, '강서', '강도', '검거', 5),
 (2020, '강서', '강간,추행', '발생', 265),
 (2020, '강서', '강간,추행', '검거', 222),
 (2020, '강서', '절도', '발생', 1689),
 (2020, '강서', '절도', '검거', 1070),
 (2020, '강서', '폭력', '발생', 2445),
 (2020, '강서', '폭력', '검거', 2087),
 (2020, '강동', '살인', '발생', 3),
 (2020, '강동', '살인', '검거', 3),
 (2020, '강동', '강도', '발생', 15),
 (2020, '강동', '강도', '검거', 14),
 (2020, '강동', '강간,추행', '발생', 188),
 (2020, '강동', '강간,추행', '검거', 167),
 (2020, '강동', '절도', '발생', 1640),
 (2020, '강동', '절도', '검거', 781),
 (2020, '강동', '폭력', '발생', 1942),
 (2020, '강동', '폭력', '검거', 1697),
 (2020, '종암', '살인', '발생', 4),
 (2020, '종암', '살인', '검거', 4),
 (2020, '종암', '강도', '발생', 1),
 (2020, '종암', '강도', '검거', 0),
 (2020, '종암', '강간', '발생', 47),
 (2020, '종암', '강간', '검거', 44),
 (2020, '종암', '절도', '발생', 549),
 (2020, '종암', '절도', '검거', 347),
 (2020, '종암', '폭력', '발생', 758),
 (2020, '종암', '폭력', '검거', 630),
 (2020, '구로', '살인', '발생', 6),
 (2020, '구로', '살인', '검거', 6),
 (2020, '구로', '강도', '발생', 5),
 (2020, '구로', '강도', '검거', 5),
 (2020, '구로', '강간,추행', '발생', 197),
 (2020, '구로', '강간,추행', '검거', 142),
 (2020, '구로', '절도', '발생', 1763),
 (2020, '구로', '절도', '검거', 1008),
 (2020, '구로', '폭력', '발생', 2204),
 (2020, '구로', '폭력', '검거', 1823),
 (2020, '서초', '살인', '발생', 4),
 (2020, '서초', '살인', '검거', 4),
 (2020, '서초', '강도', '발생', 5),
 (2020, '서초', '강도', '검거', 3),
 (2020, '서초', '강간,추행', '발생', 333),
 (2020, '서초', '강간,추행', '검거', 253),
 (2020, '서초', '절도', '발생', 1673),
 (2020, '서초', '절도', '검거', 801),
 (2020, '서초', '폭력', '발생', 1750),
 (2020, '서초', '폭력', '검거', 1415),
 (2020, '양천', '살인', '발생', 5),
 (2020, '양천', '살인', '검거', 5),
 (2020, '양천', '강도', '발생', 3),
 (2020, '양천', '강도', '검거', 3),
 (2020, '양천', '강간', '발생', 109),
 (2020, '양천', '강간', '검거', 90),
 (2020, '양천', '절도', '발생', 1517),
 (2020, '양천', '절도', '검거', 718),
 (2020, '양천', '폭력', '발생', 1582),
 (2020, '양천', '폭력', '검거', 1270),
 (2020, '송파', '살인', '발생', 6),
 (2020, '송파', '살인', '검거', 6),
 (2020, '송파', '강도', '발생', 13),
 (2020, '송파', '강도', '검거', 17),
 (2020, '송파', '강간,추행', '발생', 287),
 (2020, '송파', '강간,추행', '검거', 235),
 (2020, '송파', '절도', '발생', 2429),
 (2020, '송파', '절도', '검거', 1006),
 (2020, '송파', '폭력', '발생', 2675),
 (2020, '송파', '폭력', '검거', 2280),
 (2020, '노원', '살인', '발생', 4),
 (2020, '노원', '살인', '검거', 3),
 (2020, '노원', '강도', '발생', 3),
 (2020, '노원', '강도', '검거', 3),
 (2020, '노원', '강간,추행', '발생', 169),
 (2020, '노원', '강간,추행', '검거', 148),
 (2020, '노원', '절도', '발생', 1404),
 (2020, '노원', '절도', '검거', 646),
 (2020, '노원', '폭력', '발생', 2163),
 (2020, '노원', '폭력', '검거', 1781),
 (2020, '방배', '살인', '발생', 1),
 (2020, '방배', '살인', '검거', 1),
 (2020, '방배', '강도', '발생', 1),
 (2020, '방배', '강도', '검거', 1),
 (2020, '방배', '강간', '발생', 63),
 (2020, '방배', '강간', '검거', 50),
 (2020, '방배', '절도', '발생', 348),
 (2020, '방배', '절도', '검거', 159),
 (2020, '방배', '폭력', '발생', 423),
 (2020, '방배', '폭력', '검거', 365),
 (2020, '은평', '살인', '발생', 1),
 (2020, '은평', '살인', '검거', 1),
 (2020, '은평', '강도', '발생', 1),
 (2020, '은평', '강도', '검거', 1),
 (2020, '은평', '강간,추행', '발생', 95),
 (2020, '은평', '강간,추행', '검거', 74),
 (2020, '은평', '절도', '발생', 839),
 (2020, '은평', '절도', '검거', 434),
 (2020, '은평', '폭력', '발생', 1092),
 (2020, '은평', '폭력', '검거', 956),
 (2020, '도봉', '살인', '발생', 0),
 (2020, '도봉', '살인', '검거', 0),
 (2020, '도봉', '강도', '발생', 2),
 (2020, '도봉', '강도', '검거', 2),
 (2020, '도봉', '강간', '발생', 82),
 (2020, '도봉', '강간', '검거', 87),
 (2020, '도봉', '절도', '발생', 861),
 (2020, '도봉', '절도', '검거', 379),
 (2020, '도봉', '폭력', '발생', 1234),
 (2020, '도봉', '폭력', '검거', 1022),
 (2020, '수서', '살인', '발생', 1),
 (2020, '수서', '살인', '검거', 2),
 (2020, '수서', '강도', '발생', 2),
 (2020, '수서', '강도', '검거', 1),
 (2020, '수서', '강간,추행', '발생', 195),
 (2020, '수서', '강간,추행', '검거', 194),
 (2020, '수서', '절도', '발생', 1010),
 (2020, '수서', '절도', '검거', 475),
 (2020, '수서', '폭력', '발생', 1394),
 (2020, '수서', '폭력', '검거', 1200),
 (2020, '중부', '살인', '발생', 1),
 (2020, '중부', '살인', '검거', 1),
 (2020, '중부', '강도', '발생', 3),
 (2020, '중부', '강도', '검거', 4),
 (2020, '중부', '강간,추행', '발생', 113),
 (2020, '중부', '강간,추행', '검거', 76),
 (2020, '중부', '절도', '발생', 943),
 (2020, '중부', '절도', '검거', 495),
 (2020, '중부', '폭력', '발생', 997),
 (2020, '중부', '폭력', '검거', 830),
 (2020, '종로', '살인', '발생', 9),
 (2020, '종로', '살인', '검거', 6),
 (2020, '종로', '강도', '발생', 4),
 (2020, '종로', '강도', '검거', 4),
 (2020, '종로', '강간,추행', '발생', 115),
 (2020, '종로', '강간,추행', '검거', 93),
 (2020, '종로', '절도', '발생', 602),
 (2020, '종로', '절도', '검거', 284),
 (2020, '종로', '폭력', '발생', 964),
 (2020, '종로', '폭력', '검거', 792),
 (2020, '남대문', '살인', '발생', 1),
 (2020, '남대문', '살인', '검거', 1),
 (2020, '남대문', '강도', '발생', 2),
 (2020, '남대문', '강도', '검거', 2),
 (2020, '남대문', '강간,추행', '발생', 73),
 (2020, '남대문', '강간,추행', '검거', 52),
 (2020, '남대문', '절도', '발생', 699),
 (2020, '남대문', '절도', '검거', 368),
 (2020, '남대문', '폭력', '발생', 579),
 (2020, '남대문', '폭력', '검거', 494),
 (2020, '서대문', '살인', '발생', 3),
 (2020, '서대문', '살인', '검거', 3),
 (2020, '서대문', '강도', '발생', 2),
 (2020, '서대문', '강도', '검거', 1),
 (2020, '서대문', '강간,추행', '발생', 159),
 (2020, '서대문', '강간,추행', '검거', 149),
 (2020, '서대문', '절도', '발생', 1077),
 (2020, '서대문', '절도', '검거', 524),
 (2020, '서대문', '폭력', '발생', 1292),
 (2020, '서대문', '폭력', '검거', 1029),
 (2020, '혜화', '살인', '발생', 0),
 (2020, '혜화', '살인', '검거', 0),
 (2020, '혜화', '강도', '발생', 3),
 (2020, '혜화', '강도', '검거', 3),
 (2020, '혜화', '강간,추행', '발생', 77),
 (2020, '혜화', '강간,추행', '검거', 53),
 (2020, '혜화', '절도', '발생', 581),
 (2020, '혜화', '절도', '검거', 310),
 (2020, '혜화', '폭력', '발생', 747),
 (2020, '혜화', '폭력', '검거', 628),
 (2020, '용산', '살인', '발생', 5),
 (2020, '용산', '살인', '검거', 3),
 (2020, '용산', '강도', '발생', 6),
 (2020, '용산', '강도', '검거', 6),
 (2020, '용산', '강간,추행', '발생', 230),
 (2020, '용산', '강간,추행', '검거', 186),
 (2020, '용산', '절도', '발생', 1111),
 (2020, '용산', '절도', '검거', 534),
 (2020, '용산', '폭력', '발생', 1617),
 (2020, '용산', '폭력', '검거', 1327),
 (2020, '성북', '살인', '발생', 0),
 (2020, '성북', '살인', '검거', 0),
 (2020, '성북', '강도', '발생', 2),
 (2020, '성북', '강도', '검거', 2),
 (2020, '성북', '강간', '발생', 95),
 (2020, '성북', '강간', '검거', 77),
 (2020, '성북', '절도', '발생', 439),
 (2020, '성북', '절도', '검거', 233),
 (2020, '성북', '폭력', '발생', 672),
 (2020, '성북', '폭력', '검거', 610),
 (2020, '동대문', '살인', '발생', 10),
 (2020, '동대문', '살인', '검거', 8),
 (2020, '동대문', '강도', '발생', 6),
 (2020, '동대문', '강도', '검거', 5),
 (2020, '동대문', '강간,추행', '발생', 161),
 (2020, '동대문', '강간,추행', '검거', 142),
 (2020, '동대문', '절도', '발생', 1440),
 (2020, '동대문', '절도', '검거', 713),
 (2020, '동대문', '폭력', '발생', 1784),
 (2020, '동대문', '폭력', '검거', 1597),
 (2020, '마포', '살인', '발생', 9),
 (2020, '마포', '살인', '검거', 8),
 (2020, '마포', '강도', '발생', 4),
 (2020, '마포', '강도', '검거', 3),
 (2020, '마포', '강간,추행', '발생', 348),
 (2020, '마포', '강간,추행', '검거', 287),
 (2020, '마포', '절도', '발생', 1483),
 (2020, '마포', '절도', '검거', 679),
 (2020, '마포', '폭력', '발생', 1844),
 (2020, '마포', '폭력', '검거', 1557),
 (2020, '영등포', '살인', '발생', 7),
 (2020, '영등포', '살인', '검거', 4),
 (2020, '영등포', '강도', '발생', 6),
 (2020, '영등포', '강도', '검거', 5),
 (2020, '영등포', '강간,추행', '발생', 315),
 (2020, '영등포', '강간,추행', '검거', 252),
 (2020, '영등포', '절도', '발생', 2188),
 (2020, '영등포', '절도', '검거', 953),
 (2020, '영등포', '폭력', '발생', 2701),
 (2020, '영등포', '폭력', '검거', 2157),
 (2020, '성동', '살인', '발생', 5),
 (2020, '성동', '살인', '검거', 5),
 (2020, '성동', '강도', '발생', 3),
 (2020, '성동', '강도', '검거', 3),
 (2020, '성동', '강간,추행', '발생', 115),
 (2020, '성동', '강간,추행', '검거', 98),
 (2020, '성동', '절도', '발생', 1016),
 (2020, '성동', '절도', '검거', 565),
 (2020, '성동', '폭력', '발생', 1223),
 (2020, '성동', '폭력', '검거', 1103),
 (2020, '동작', '살인', '발생', 1),
 (2020, '동작', '살인', '검거', 1),
 (2020, '동작', '강도', '발생', 1),
 (2020, '동작', '강도', '검거', 2),
 (2020, '동작', '강간,추행', '발생', 226),
 (2020, '동작', '강간,추행', '검거', 121),
 (2020, '동작', '절도', '발생', 1341),
 (2020, '동작', '절도', '검거', 592),
 (2020, '동작', '폭력', '발생', 1631),
 (2020, '동작', '폭력', '검거', 1370),
 (2020, '광진', '살인', '발생', 2),
 (2020, '광진', '살인', '검거', 2),
 (2020, '광진', '강도', '발생', 4),
 (2020, '광진', '강도', '검거', 4),
 (2020, '광진', '강간,추행', '발생', 255),
 (2020, '광진', '강간,추행', '검거', 224),
 (2020, '광진', '절도', '발생', 1664),
 (2020, '광진', '절도', '검거', 874),
 (2020, '광진', '폭력', '발생', 1676),
 (2020, '광진', '폭력', '검거', 1407),
 (2020, '서부', '살인', '발생', 3),
 (2020, '서부', '살인', '검거', 3),
 (2020, '서부', '강도', '발생', 3),
 (2020, '서부', '강도', '검거', 2),
 (2020, '서부', '강간,추행', '발생', 76),
 (2020, '서부', '강간,추행', '검거', 71),
 (2020, '서부', '절도', '발생', 532),
 (2020, '서부', '절도', '검거', 322),
 (2020, '서부', '폭력', '발생', 748),
 (2020, '서부', '폭력', '검거', 667),
 (2020, '강북', '살인', '발생', 9),
 (2020, '강북', '살인', '검거', 8),
 (2020, '강북', '강도', '발생', 5),
 (2020, '강북', '강도', '검거', 4),
 (2020, '강북', '강간,추행', '발생', 159),
 (2020, '강북', '강간,추행', '검거', 132),
 (2020, '강북', '절도', '발생', 780),
 (2020, '강북', '절도', '검거', 490),
 (2020, '강북', '폭력', '발생', 1817),
 (2020, '강북', '폭력', '검거', 1625),
 (2020, '금천', '살인', '발생', 4),
 (2020, '금천', '살인', '검거', 4),
 (2020, '금천', '강도', '발생', 7),
 (2020, '금천', '강도', '검거', 6),
 (2020, '금천', '강간,추행', '발생', 117),
 (2020, '금천', '강간,추행', '검거', 93),
 (2020, '금천', '절도', '발생', 999),
 (2020, '금천', '절도', '검거', 553),
 (2020, '금천', '폭력', '발생', 1471),
 (2020, '금천', '폭력', '검거', 1310),
 (2020, '중랑', '살인', '발생', 10),
 (2020, '중랑', '살인', '검거', 9),
 (2020, '중랑', '강도', '발생', 5),
 (2020, '중랑', '강도', '검거', 6),
 (2020, '중랑', '강간,추행', '발생', 183),
 (2020, '중랑', '강간,추행', '검거', 153),
 (2020, '중랑', '절도', '발생', 1506),
 (2020, '중랑', '절도', '검거', 889),
 (2020, '중랑', '폭력', '발생', 2022),
 (2020, '중랑', '폭력', '검거', 1724),
 (2020, '강남', '살인', '발생', 5),
 (2020, '강남', '살인', '검거', 3),
 (2020, '강남', '강도', '발생', 12),
 (2020, '강남', '강도', '검거', 10),
 (2020, '강남', '강간,추행', '발생', 513),
 (2020, '강남', '강간,추행', '검거', 433),
 (2020, '강남', '절도', '발생', 1941),
 (2020, '강남', '절도', '검거', 1016),
 (2020, '강남', '폭력', '발생', 2283),
 (2020, '강남', '폭력', '검거', 1911),
 (2020, '관악', '살인', '발생', 12),
 (2020, '관악', '살인', '검거', 12),
 (2020, '관악', '강도', '발생', 3),
 (2020, '관악', '강도', '검거', 3),
 (2020, '관악', '강간,추행', '발생', 403),
 (2020, '관악', '강간,추행', '검거', 351),
 (2020, '관악', '절도', '발생', 2229),
 (2020, '관악', '절도', '검거', 1137),
 (2020, '관악', '폭력', '발생', 2614),
 (2020, '관악', '폭력', '검거', 2355),
 (2020, '강서', '살인', '발생', 10),
 (2020, '강서', '살인', '검거', 9),
 (2020, '강서', '강도', '발생', 6),
 (2020, '강서', '강도', '검거', 5),
 (2020, '강서', '강간,추행', '발생', 265),
 (2020, '강서', '강간,추행', '검거', 222),
 (2020, '강서', '절도', '발생', 1689),
 (2020, '강서', '절도', '검거', 1070),
 (2020, '강서', '폭력', '발생', 2445),
 (2020, '강서', '폭력', '검거', 2087),
 (2020, '강동', '살인', '발생', 3),
 (2020, '강동', '살인', '검거', 3),
 (2020, '강동', '강도', '발생', 15),
 (2020, '강동', '강도', '검거', 14),
 (2020, '강동', '강간,추행', '발생', 188),
 (2020, '강동', '강간,추행', '검거', 167),
 (2020, '강동', '절도', '발생', 1640),
 (2020, '강동', '절도', '검거', 781),
 (2020, '강동', '폭력', '발생', 1942),
 (2020, '강동', '폭력', '검거', 1697),
 (2020, '종암', '살인', '발생', 4),
 (2020, '종암', '살인', '검거', 4),
 (2020, '종암', '강도', '발생', 1),
 (2020, '종암', '강도', '검거', 0),
 (2020, '종암', '강간', '발생', 47),
 (2020, '종암', '강간', '검거', 44),
 (2020, '종암', '절도', '발생', 549),
 (2020, '종암', '절도', '검거', 347),
 (2020, '종암', '폭력', '발생', 758),
 (2020, '종암', '폭력', '검거', 630),
 (2020, '구로', '살인', '발생', 6),
 (2020, '구로', '살인', '검거', 6),
 (2020, '구로', '강도', '발생', 5),
 (2020, '구로', '강도', '검거', 5),
 (2020, '구로', '강간,추행', '발생', 197),
 (2020, '구로', '강간,추행', '검거', 142),
 (2020, '구로', '절도', '발생', 1763),
 (2020, '구로', '절도', '검거', 1008),
 (2020, '구로', '폭력', '발생', 2204),
 (2020, '구로', '폭력', '검거', 1823),
 (2020, '서초', '살인', '발생', 4),
 (2020, '서초', '살인', '검거', 4),
 (2020, '서초', '강도', '발생', 5),
 (2020, '서초', '강도', '검거', 3),
 (2020, '서초', '강간,추행', '발생', 333),
 (2020, '서초', '강간,추행', '검거', 253),
 (2020, '서초', '절도', '발생', 1673),
 (2020, '서초', '절도', '검거', 801),
 (2020, '서초', '폭력', '발생', 1750),
 (2020, '서초', '폭력', '검거', 1415),
 (2020, '양천', '살인', '발생', 5),
 (2020, '양천', '살인', '검거', 5),
 (2020, '양천', '강도', '발생', 3),
 (2020, '양천', '강도', '검거', 3),
 (2020, '양천', '강간', '발생', 109),
 (2020, '양천', '강간', '검거', 90),
 (2020, '양천', '절도', '발생', 1517),
 (2020, '양천', '절도', '검거', 718),
 (2020, '양천', '폭력', '발생', 1582),
 (2020, '양천', '폭력', '검거', 1270),
 (2020, '송파', '살인', '발생', 6),
 (2020, '송파', '살인', '검거', 6),
 (2020, '송파', '강도', '발생', 13),
 (2020, '송파', '강도', '검거', 17),
 (2020, '송파', '강간,추행', '발생', 287),
 (2020, '송파', '강간,추행', '검거', 235),
 (2020, '송파', '절도', '발생', 2429),
 (2020, '송파', '절도', '검거', 1006),
 (2020, '송파', '폭력', '발생', 2675),
 (2020, '송파', '폭력', '검거', 2280),
 (2020, '노원', '살인', '발생', 4),
 (2020, '노원', '살인', '검거', 3),
 (2020, '노원', '강도', '발생', 3),
 (2020, '노원', '강도', '검거', 3),
 (2020, '노원', '강간,추행', '발생', 169),
 (2020, '노원', '강간,추행', '검거', 148),
 (2020, '노원', '절도', '발생', 1404),
 (2020, '노원', '절도', '검거', 646),
 (2020, '노원', '폭력', '발생', 2163),
 (2020, '노원', '폭력', '검거', 1781),
 (2020, '방배', '살인', '발생', 1),
 (2020, '방배', '살인', '검거', 1),
 (2020, '방배', '강도', '발생', 1),
 (2020, '방배', '강도', '검거', 1),
 (2020, '방배', '강간', '발생', 63),
 (2020, '방배', '강간', '검거', 50),
 (2020, '방배', '절도', '발생', 348),
 (2020, '방배', '절도', '검거', 159),
 (2020, '방배', '폭력', '발생', 423),
 (2020, '방배', '폭력', '검거', 365),
 (2020, '은평', '살인', '발생', 1),
 (2020, '은평', '살인', '검거', 1),
 (2020, '은평', '강도', '발생', 1),
 (2020, '은평', '강도', '검거', 1),
 (2020, '은평', '강간,추행', '발생', 95),
 (2020, '은평', '강간,추행', '검거', 74),
 (2020, '은평', '절도', '발생', 839),
 (2020, '은평', '절도', '검거', 434),
 (2020, '은평', '폭력', '발생', 1092),
 (2020, '은평', '폭력', '검거', 956),
 (2020, '도봉', '살인', '발생', 0),
 (2020, '도봉', '살인', '검거', 0),
 (2020, '도봉', '강도', '발생', 2),
 (2020, '도봉', '강도', '검거', 2),
 (2020, '도봉', '강간', '발생', 82),
 (2020, '도봉', '강간', '검거', 87),
 (2020, '도봉', '절도', '발생', 861),
 (2020, '도봉', '절도', '검거', 379),
 (2020, '도봉', '폭력', '발생', 1234),
 (2020, '도봉', '폭력', '검거', 1022),
 (2020, '수서', '살인', '발생', 1),
 (2020, '수서', '살인', '검거', 2),
 (2020, '수서', '강도', '발생', 2),
 (2020, '수서', '강도', '검거', 1),
 (2020, '수서', '강간,추행', '발생', 195),
 (2020, '수서', '강간,추행', '검거', 194),
 (2020, '수서', '절도', '발생', 1010),
 (2020, '수서', '절도', '검거', 475),
 (2020, '수서', '폭력', '발생', 1394),
 (2020, '수서', '폭력', '검거', 1200)]

In [40]:
remote.close()

In [41]:
import pandas as pd

In [43]:
df = pd.DataFrame(result)
df.head()

      0   1      2   3    4
0  2020  중부     살인  발생    1
1  2020  중부     살인  검거    1
2  2020  중부     강도  발생    3
3  2020  중부     강도  검거    4
4  2020  중부  강간,추행  발생  113

In [70]:
df = pd.read_csv("Seoul_CCTV.csv")
df.head()

   기관명    소계  2013년도 이전  2014년  2015년  2016년
0  강남구  3238       1292    430    584    932
1  강동구  1010        379     99    155    377
2  강북구   831        369    120    138    204
3  강서구   911        388    258    184     81
4  관악구  2109        846    260    390    613

In [48]:
remote = mysql.connector.connect(
    host = 'database-1.cjnz1ulpkijp.ap-southeast-2.rds.amazonaws.com',
    port=3306,
    user='admin',
    password="mooltisue305!",
    database = 'zerobase')

In [ ]:
cr = remote.cursor(buffered=True)
cr.execute('create table Seoul_cctv(name varchar(16), num INT, a INT, b INT, c INT, d INT)')

In [76]:
sql = """Insert into Seoul_cctv Values(%s,%s,%s,%s,%s,%s)"""
cr = remote.cursor(buffered=True)

In [77]:
for i,rows in df.iterrows():
    cr.execute(sql,tuple(rows))
    print(tuple(rows))
    remote.commit()

('강남구', 3238, 1292, 430, 584, 932)
('강동구', 1010, 379, 99, 155, 377)
('강북구', 831, 369, 120, 138, 204)
('강서구', 911, 388, 258, 184, 81)
('관악구', 2109, 846, 260, 390, 613)
('광진구', 878, 573, 78, 53, 174)
('구로구', 1884, 1142, 173, 246, 323)
('금천구', 1348, 674, 51, 269, 354)
('노원구', 1566, 542, 57, 451, 516)
('도봉구', 825, 238, 159, 42, 386)
('동대문구', 1870, 1070, 23, 198, 579)
('동작구', 1302, 544, 341, 103, 314)
('마포구', 980, 314, 118, 169, 379)
('서대문구', 1254, 844, 50, 68, 292)
('서초구', 2297, 1406, 157, 336, 398)
('성동구', 1327, 730, 91, 241, 265)
('성북구', 1651, 1009, 78, 360, 204)
('송파구', 1081, 529, 21, 68, 463)
('양천구', 2482, 1843, 142, 30, 467)
('영등포구', 1277, 495, 214, 195, 373)
('용산구', 2096, 1368, 218, 112, 398)
('은평구', 2108, 1138, 224, 278, 468)
('종로구', 1619, 464, 314, 211, 630)
('중구', 1023, 413, 190, 72, 348)
('중랑구', 916, 509, 121, 177, 109)

In [79]:
cr.execute("select * from Seoul_cctv")

result = cr.fetchall()
for row in result:
    print(row)

('강남구', 3238, 1292, 430, 584, 932)
('강동구', 1010, 379, 99, 155, 377)
('강북구', 831, 369, 120, 138, 204)
('강서구', 911, 388, 258, 184, 81)
('관악구', 2109, 846, 260, 390, 613)
('광진구', 878, 573, 78, 53, 174)
('구로구', 1884, 1142, 173, 246, 323)
('금천구', 1348, 674, 51, 269, 354)
('노원구', 1566, 542, 57, 451, 516)
('도봉구', 825, 238, 159, 42, 386)
('동대문구', 1870, 1070, 23, 198, 579)
('동작구', 1302, 544, 341, 103, 314)
('마포구', 980, 314, 118, 169, 379)
('서대문구', 1254, 844, 50, 68, 292)
('서초구', 2297, 1406, 157, 336, 398)
('성동구', 1327, 730, 91, 241, 265)
('성북구', 1651, 1009, 78, 360, 204)
('송파구', 1081, 529, 21, 68, 463)
('양천구', 2482, 1843, 142, 30, 467)
('영등포구', 1277, 495, 214, 195, 373)
('용산구', 2096, 1368, 218, 112, 398)
('은평구', 2108, 1138, 224, 278, 468)
('종로구', 1619, 464, 314, 211, 630)
('중구', 1023, 413, 190, 72, 348)
('중랑구', 916, 509, 121, 177, 109)

In [80]:
df = pd.DataFrame(result)
df.tail()

      0     1     2    3    4    5
20  용산구  2096  1368  218  112  398
21  은평구  2108  1138  224  278  468
22  종로구  1619   464  314  211  630
23   중구  1023   413  190   72  348
24  중랑구   916   509  121  177  109